### ISSUE TITLE
Data Access Object(s)

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1]
_**Layer: Data Source**_

> **The Components need a way to read/write entities to the database.
> This needs to be easy to extend/configure for additional entity types.**

Previously we used:
- `appDB`  for general interaction and authentication with `pouchDB`.
- `DbManager` to retrieve objects with `get(id)` or `getAll()`; abstract class extended for each "entity type" (e.g. ChildManager, SchoolManager)
- `AbstractModel` to allow each entity to `update` and `delete` itself; abstract class extended by each "entity type" (e.g. Child, School) (Pattern: [Active Record](https://en.wikipedia.org/wiki/Active_record_pattern))

Things to consider:
- Are multiple DbManager types necessary?
- How to handle multiple databases? (e.g. a separate pouchDB for files)

**Comment by sebastian-leidig** [comment]
After discussion and a lot of thought and trial I would propose the following now:

Domain logic is implemented in plain old TypeScript classes. The base class for these is `Entity`. Entities do not know or care about how they are written to or retrieved from the database.

`EntityMapperService` serves as a the default and generic [Data Mapper](https://en.wikipedia.org/wiki/Data_mapper_pattern) that translates between `Entity` (or other "Entity Types") and the `Database`. To save an Entity instance to the database or load one from it, the `EntityMapperService` is injected and its functions find/save/remove are used. (If some Entity Type needs to be written to the db in some unusual way, one can implement a special Mapper for this)

The actual database access is split into two classes (also see #9):
- `Database` providing functions to get/put/remove objects (a wrapper of a PouchDB instance)
- `DatabaseManagerService` providing functions to authenticate/sync/... and a usable `Database` instance to be injected into other components of the app

**Comment by sebastian-leidig** [comment]
This is implemented now (as part of #9 and #13 ).

Normally there should be no need to use `Database` (or even `DatabaseManagerService`) anywhere to load/save/remove data in the database. This is done using the `EntityMapperService` (or a custom MapperService extending `EntityMapperService` for special entity types).

## Example: load and save data in the database

    export class ExampleService {
    
        // get EntityMapperService through Dependency Injection
        constructor(private _entityMapper: EntityMapperService) {  }
    
        private getExampleUser() {
            // load requires an instance of the Entity (sub)type as second argument
            this._entityMapper.load<User>("x-user", new User())
                .then(function(userEntity) {
                    // userEntity is an instance of class User containing the information from the database
                    console.info(userEntity);
                })
                .catch(function(error) {
                    if(error.status == 404) {
                        console.info("no record with this _id in database");
                    }
                });
        }
    }
