### ISSUE TITLE
Release Notes popup getting lost during reloads for new version

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1071]
The popup showing release notes to users in the app when they first open a new version is not shown consistently anymore.

It seems that the popup sometimes is briefly opened but then the site reloads again (?) after which the popup is lost.

**Comment by TheSlimvReal** [comment]
What is currently happening:

For app updates
1. New version is found
2. "update-<old-version>" is written to local storage
3. update snackbar is shown
3.1. If update snackbar is clicked: "<old-version>" is written to local storage and page reloaded
3.2. If page is manually reloaded/closed-and-reopened "<old-version>" is written to local storage and page is reloaded (this is necessary on some phones where opening a PWA does not automatically reload it and therefore new updates are not correctly installed)

For version popup
1. Version from last login is read from local storage
2. If current version differs, the release notes popup is shown
3. The latest version is written to the local storage

There might be race conditions between these two processes where the version change is lost during the reloads or a wrong version is read from the local storage
