### ISSUE TITLE
Export Notes/Events for a selected time period

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1076]
*As a coordinator I want to download the events of the last month in order to share the list with external stakeholders.*

**Objective**
At the moment only exporting the whole list of events / notes is possible. This list can become very long and users sometimes need to share or print events for a specific time period only (e.g. last month). Therefore a selected export should be added.

**Proposed Solutions & Alternatives**
- add filter for custom time period to the Notes List
- allow export of the currently filtered data instead of the full dataset?

**Comment by TheSlimvReal** [comment]
Solved with #1117
