### ISSUE TITLE
Paginator does not initialize settings correctly

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1107]
**Describe the bug**
The paginator stores and loads its settings from the user entity. This is correctly visualized in the paginator but the connected datasource (the table) does not get correctly initialized.

**To Reproduce**
1. Go to 'Notes'
2. Click on 'show all'
3. Go to 'Reports' (leave the screen)
4. Go to 'Notes'
5. The 'show all' button looks active, but only 10 notes are displayed. Re-activating notes correctly shows all notes. The same happens when changing the page size.

**Expected behavior**
The table should update accordingly with the user settings.

**Additional context**
The problem only happens when the view is initialized.

**Comment by sleidig** [comment]
This only seems to happen for Notes, not in the Children list
