### ISSUE TITLE
Disable other sections when creating Entity in Entity Details

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1108]
**Describe the bug**
When creating a new entity through the entity details view (e.g. https://demo.aam-digital.com/child/new) the other sections (besides `Basic Information`) should be disabled. Otherwise this can be used to store a entity where required fields are not filled out.

**To Reproduce**
1. Go to 'Children'
2. Click on 'Add new '
3. Click on 'Health'
4. Click on 'Save'
5. Now a child without a name has been created

**Expected behavior**
It should not be possible to switch the tabs when creating a new entity.

**Comment by sleidig** [comment]
In the previous design (expansion panels instead of tabs) the other sections were disabled until the first save of a new entity. We could do this similarly - disabling or hiding the other tabs.
