### ISSUE TITLE
Entity Select field shows LastPass 

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1111]
**Describe the bug**
In the Entity Select (authors in Note Details, assigned users in Activity Details) input fields the LastPass browser extension somehow detects that this is a username/password input.
This should be prevented as it could confuse users wen it is automatically opening and hides the dropdown select.

I am not sure whether it happens with other password managers as well. Maybe this is more a LastPass issue.

![image](https://user-images.githubusercontent.com/33730997/154147754-5e5fb831-7104-4f16-8696-461cd70525b4.png)

**Comment by sleidig** [comment]
LastPass seems to analyze forms based on their labels / ids and suggest filling in details like name and address if it guesses this is a contact form for the user. "author" or "name" (e.g. creating a new Child) seem to trigger this. LastPass adds the small icon in these cases.

After discussing this in the team, we decided this is not too obstructive, so we won't work on any workaround to the normal LastPass behaviour causing this.
