### ISSUE TITLE
Research how app can be published in app stores

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1126]
- [ ] Check how app can be build to be published in PlayStore
- [ ] Check how app can be published in PlayStore
- [ ] Check whether app has to be updated manually or whether service workers provide updates in the background
- [ ] Check whats the state with IOS/AppStore

**Comment by sleidig** [comment]
We have not faced issues with the web app approach at any time recently, so it is unlikely the additional overhead for publishing and maintenance is worth it. Closing this for now.
