### ISSUE TITLE
Feature: Import UI

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1135]
_As a user I want to import data from other sources through a CSV file without requiring any technical support, even if I am not familiar with concepts like data formats, etc._

https://docs.google.com/document/d/1K8eNgKXDkvVN8OuRG87YB07izPdtFExLTG1Mc9vBVJY/edit

---

The base feature with a UI is developed in PR #1059 . This issue is a summary thread to discuss further improvements and user stories, which we can split out into their own issues to be implemented.

see Milestone [Import UI](https://github.com/Aam-Digital/ndb-core/milestone/23)
- [x] #974
- [x] #975
- [x] allow undo of import
- [x] #1771
- [x] #1772
- [x] map string values from import to configurable-enum values in app
- [x] map string values from import to boolean values in app
- [x] automatically infer date format
- [x] test date format to be able to parse dates in that sheet/column
- [ ] #1768
- [ ] split column by space (e.g. from name to first + last name)

Smaller bugs:

- [x] #1799
- [ ] import config and auto assignment sometimes uses same column multiple times
- [ ] trim spaces on values for a better mapping experience (probably also ignore case)

**Comment by TheSlimvReal** [comment]
Inspiration by an accounting software to import transactions that also uses a column mapping approach.

![image](https://user-images.githubusercontent.com/33730997/158783172-4355aa17-7d42-439b-a097-c470f1279cc0.png)

**Comment by TheSlimvReal** [comment]
Improve usability of undoing/viewing previous imports
- [ ] Replace usage of `transactionID` with a (new) optional property `importedAt` in the `Entity` class that is set with the timestamp `YYYY-MM-DD HH:MM:SS` of the import
- [ ] Create a new entity (some name like `ImportMetaData`) that stores for each import the timestamp of the import, the amount and type of entities imported and the configuration of the import (entity type, date-formatting, column mapping, ...)
- [ ] Show `ImportMetaData` entities in import widget and allow to delete a recent import or use the configuration of a recent import
