### ISSUE TITLE
Feature: File Uploads

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1136]
_As a user I want to upload files from my local device into the app directly. This can be to update participants' photos or attach documents, etc._

---
This is a summary issue to discuss our general approach of handling file uploads into Aam Digital. How do we store and secure files? Do we use integrations with systems like Nextcloud (and how do we integrate, #472 , #423 ). Specific tasks and user-facing features get their own separate issues to be implemented and are listed here.

Features:
- allow users to attach documents to notes: #89

**Comment by TheSlimvReal** [comment]
Files that end up on a server should be checked for viruses/converted to a safe format.
