### ISSUE TITLE
simplify & clean up the Import UI steps

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1156]
Our new Import Component allows users to go through an easy step-by-step process to import entities from a csv file (see #1135). The current design of the component could be polished a bit further. Some ideas:

- [ ] maybe combine the various config steps into one screen to make their interrelation clearer (loading config from file + select type + date format + maybe transaction ID)?
- [ ] the "next" and "back" buttons feel a bit lost to me. also, they are not disabled when the next step is not possible yet
- [ ] it is not super clear that some parts are optional (although it is written clearly, it's easy to overlook)
- [ ] add more explanation text for each step
- [ ] add validation and/or examples for Date format
- [ ] what does "Reset" on the last step mean/do?
- [ ] make the import id step optional to not confuse less experienced users

**Comment by TheSlimvReal** [comment]
Closing this as most of it is not relevant in the current UI anymore
