### ISSUE TITLE
Allow to use `bmi` column when defining columns through config

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1170]
When using the `HealthCheckupComponent` it is possible to define the visible columns through the config. 
The problem is that the `bmi` column cannot be created through the config (it requires a function) and is only available when no config is provided.
A simple solution could be to check if the column `bmi` is in the list provided through the config in `onInitFromDynamicConfig` and if yes, use the custom `bmi` column definition that is hardcoded in the component.

**Comment by TheSlimvReal** [comment]
Are more advanced solution would be to provide a custom component `DisplayBmi` that can be used directly.

**Comment by sleidig** [comment]
@christophscheuing this is similar to your recent work, maybe you want to look at creating a custom `DisplayBmi` component to make our system more flexible and generic.

**Comment by sleidig** [comment]
done using the existing HealthCheck getter `bmi`
