### ISSUE TITLE
Change order of changelog

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1189]
In the changelog popup it should first show the bigger changes (e.g. features) before the bugfixes to have the most important/significant changes first.

Currently it looks like this
![image](https://user-images.githubusercontent.com/33730997/162564633-53e87e8b-716c-4c0a-99a3-500efc694a90.png)

**Comment by sleidig** [comment]
see https://github.com/conventional-changelog/conventional-changelog/issues/702

**Comment by sleidig** [comment]
closing this in favor of custom editing the GitHub Release notes for major releases. To make them more user friendly we need some manual work anyway ...
