### ISSUE TITLE
Generalize inactive status

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1190]
Currently children can be marked as inactive and will not be shown in the default list views or dropdown selection.
This feature should be generalized so it can also be used for Users, School, etc.

A similar flag is also used for the `ChildSchoolRelation` where  a "active" status is calculated based on the start and end date.
Maybe this can also be included but as the logic is a bit different there this is not super necessary.
What can be done is to have the generic `isActive` function on the `Entity` class which can then be overwritten by subclasses.

**Comment by sleidig** [comment]
This would also help block users from selecting a school/group that is missing some validation steps (e.g. signing an agreement with the organization).

**Comment by sleidig** [comment]
As "Recurring Activities" should not be deleted, here also an option to archive them and hide them from the common screens is important
