### ISSUE TITLE
Color coding of attendance months broken

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1205]
It seems the rows in the monthly summarized attendance table (Attendance tab of child details) is always getting a orange background instead of the previously implemented color coding that was red for low attendance rates and not highlighted (or green?) for high rates.

![image](https://user-images.githubusercontent.com/1682541/163448537-9e884b68-5c15-48a1-bc66-3662c37b3196.png)

**Comment by TheSlimvReal** [comment]
We might have to adjust the demo data generation to have less *warning* events. Currently the mean is 66% attendance

**Comment by sleidig** [comment]
There (sometimes?) seems to be an issue beyond that (see screenshot). I am looking at child details, not activity details
