### ISSUE TITLE
Form errors are not correctly shown

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1207]
**Describe the bug**
Popups do not show invalid fields anymore

**To Reproduce**
1. Go to a child
2. Click on 'Education'
3. Click on '+'
4. Click on 'save'
5. Open console
6. See error in the console, but view does not display anything

**Expected behavior**
The invalid field should disable the save button and be marked as invalid.
Also the error message should be shown in a snackbar.

**Comment by sleidig** [comment]
is this related to #914?

**Comment by TheSlimvReal** [comment]
No this is mostly a regression due to recent refactorings.
