### ISSUE TITLE
Dashboard widget: Notes needing follow-up

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1238]
*As a social worker I want to immediately see the issues that need my attention from the dashboard without navigating to other screens like the notes list.*

**Objective**
Users can give notes a status of "Needs follow-up" or "Urgent" to flag them as needing attention. This allows them to be filtered for in the Notes list. To draw more attention to these notes, a dashboard widget to list these was requested. This could look similar to other widgets listing cases with absences.

**Proposed Solutions & Alternatives**
Dashboard widget showing count of notes with urgent/follow-up (allow setting via config) status. List all notes with date, title in the paginated widget details.
Allow (optionally, via config) to only display notes assigned to current user.

**Comment by TheSlimvReal** [comment]
This would also go very well with user permissions where a user only has read access for the notes to which he/she is tagged.
