### ISSUE TITLE
Optimize for mobile (small screens)

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#124]
The UI needs to be tuned to work well on smartphones:
- [x] side menu hidden on smaller screens
- [x] responsive `EntitySubrecordComponent` (hides columns based on screen size): #197/#198
- [x] dashboard widgets keep fixed width and are responsively shown below each other on smaller screens: #205
- ... ?
----
- [x] Test the full app for usability on smartphone (or with Chrome's dev tools viewing at different resolutions) and close this issue.

**Comment by codingfabi** [comment]
should we just rework the application css and html or should we consider using a angular api for mobile apps?
if we just rework css and html, could we make a list with modules that should be reworked?

**Comment by sleidig** [comment]
Probably better if we find some modules that help to optimize for this in the background rather than tuning everything by manual css. I know Bootstrap has stuff like that. As we are using Angular Material it would be nice if we don't have to mix in Bootstrap (although maybe they can be combined actually). For layout stuff we are using [angular flex-layout](https://github.com/angular/flex-layout/wiki/Declarative-API-Overview) currently. Maybe this has some options - or it should be replaced with something (like bootstrap) that has options for responsive design?

**Comment by codingfabi** [comment]
I looked it up and read a bit about using responsive design in angular and I came accross this thing here:
https://medium.com/@tomastrajan/how-to-build-responsive-layouts-with-bootstrap-4-and-angular-6-cfbb108d797b
maybe we should consider implementing this.
what about the priority? How often are the social workers accessing the software via phone or tablet? is it really high prio?

**Comment by codingfabi** [comment]
https://materializecss.com/
Mabye this could be an option too

**Comment by sleidig** [comment]
Does someone have an overview what UI parts still have to be reworked to be responsive?

- #197/#198 seems related

**Comment by Lorsbyjm** [comment]
We are currently working on the childrensDetails page. Most of it is already finished, but there are some bugs in it. I also changed the entiy-subrecord and DescriptionColumn class to be resizeable.
The side nav is already responsive.

**Comment by sleidig** [comment]
This looks good now after the big PR #198 . Awesome!

I have added one issue mostly for documentation, regarding the fact that adding data in EntitySubrecordComponent is currently not possible on small screens: #300
