### ISSUE TITLE
margin between menu and main view sometimes (?) missing

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1240]
On reloading the page there (sometimes?) is no margin between menu and main view (see screenshot). Zooming in the browser in/out and back to default then resets things and displays the layout properly.
![image](https://user-images.githubusercontent.com/1682541/165980863-c0ba8694-ed61-414f-af01-e5a57af1dd1e.png)

**Comment by TheSlimvReal** [comment]
This only happens when a Logo or long title is used in the side drawer which the width of the navigation menu. This is due to a wrong initial setting of the margin of the sidenav content component
