### ISSUE TITLE
Export of data from EntityListComponents / DataTables

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#126]
The user should be able to simply export (download) the data from any data-table or list component in order to continue working with the data outside of our app. For this a simple .csv export should be accessible from the UI.

see #125 (admin/backup.service.ts) for possible implementation. Probably inject the `PapaParseService` directly in the component and use it to parse to CSV from the data.
Ideally we should avoid duplicating code between all the different entity types' views and design something generic.

**Comment by Lorsbyjm** [comment]
First try to realise the csv dowload in the UI, even with douplicate code. 
Then we can assaign this to the Milestone technical Improvment and write the generic code.
But of course you can do both in one :)

**Comment by sleidig** [comment]
The csv export is already implemented in the AdminModule.
Ideally, we could develop a component that extends `MatDataTable`, adding a download button to export whatever data is displayed in a table anywhere in the app.

**Comment by mspoeri** [comment]
I will play around a little with this feature but don´t want to block anyone whose willing to implement this faster as me so i´m not going to assign it to me.

**Comment by sleidig** [comment]
The export is basically already implemented. Can be adapted or build upon the `BackupService` and then added to the relevant UIs.

https://github.com/NGO-DB/ndb-core/blob/67aad641c397fe130f8d58dec1975a90fc3ffc8d/src/app/admin/admin/admin.component.ts#L42-L45

https://github.com/NGO-DB/ndb-core/blob/67aad641c397fe130f8d58dec1975a90fc3ffc8d/src/app/admin/backup.service.ts#L28-L44

**Comment by jana47** [comment]
You can now download some data as csv in the children list component. It's not all of the data and the code is not pretty good. But the exported file looks much better and is more user-friendly than the file exported from the admin view.
Should only the admin be able to download the data? And which components need a csv export?

**Comment by sleidig** [comment]
Great that this is getting started!

Do you want to create a pull request and upload your work so far? I'll be happy to give you feedback if I can think of any improvements.

I think generally everybody should be able to download data - although we might change our minds if users start to then mostly work in excel instead of our app ;-)

Children data is most important. Schools maybe too. But in the end it would be nice to also integrate it into `EntitySubrecordComponent` so that download is available for any table.

**Comment by jana47** [comment]
I created a pull request, so you can review it. I will have a look at the EntitySubrecordComponent.
