### ISSUE TITLE
Allow users to add new fields to an entity/form

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#133]
What information about different entities is needed can change dynamically - e.g. the health programme of a project may be extended to track height and weight as well as the vaccination status of a child. The user (or admin user) should be able to add new fields and form elements to entities through the UI without need for code changes.

**Comment by codingfabi** [comment]
in my opinion, this should only be allowed for admin users to avoid (intentional or accidental) missusage by standard users.

**Comment by sleidig** [comment]
configurability has been implemented (see #526 - #493, #523 and also #222). A UI to edit the configured fields and views will be planned and implemented later.
