### ISSUE TITLE
Language change not working

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1356]
**Describe the bug**
Since the last release (which includes the update of angular 11 -> 13) the language change is not working any more.

**To Reproduce**
1. Open application
2. Select language `de`
3. `/en-US/de` is written to the URL and the not found page is openend

**Expected behavior**
It should set `/de` to the URL and open the same page is before with German translation

**Additional context**
It seems like there is a problem with the service-worker caching and nginx routing so the application serves the default language (the one you also get when there is no locale in the URL).

**Comment by sleidig** [comment]
see #1218
