### ISSUE TITLE
EditSingleEntity in EntityForm looks bad

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1357]
**Describe the bug**
When using the edit single entity component in a `EntityForm` (e.g. child-details) it looks very bad

![image](https://user-images.githubusercontent.com/33730997/178205935-5996b55f-338a-45a1-bfde-e18c7352b79d.png)

It should not take that much vertical space and look similar to the when it is used in the `RowDetails` popup (e.g. child -> education).

**Comment by sleidig** [comment]
fixed with #1434
