### ISSUE TITLE
Make child-select component into generic entity-select component

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#136]
Rather than only allowing a select list for Child entities, this should become generic to handle any kind of Entity types. Especially required for selection list of team members (`User`s) in NoteDetails.

**Comment by sleidig** [comment]
For this a more general problem has to be solved:
How can we dynamically select `app-child-block`, `app-school-block` or some other component to be used in a template based on the specific object's type?

-> This may be an interesting lead: https://medium.com/@DenysVuika/dynamic-content-in-angular-2-3c85023d9c36

**Comment by TheSlimvReal** [comment]
The `SchoolSelectComponent` was now added which also shares much of the code of the `ChildSelectComponent` (and #691). These components could be combined for a generic `EntitySelectComponent` which uses a two-way binding to either share entities or just their IDs. Also it should have a `[multi]` flag which determines whether many or just one element can be selected. If the array of the two-way binding contains some initial values, these entities or IDs should already be selected and can not be selected again.

**Comment by sleidig** [comment]
see PR #728
