### ISSUE TITLE
Export only displayed data

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1361]
Users who regularly use the export feature (accessed through the three-dot menu at the top right of list views) sometimes complain, that it exports all the data instead of just the one that they have filtered for in the list view. 

E.g. if somebody filtered the children for a certain center, when exporting the children, only the children from this center should be exported. Same goes with other selectable or text filters. In the end only the data that is shown in the table should be exported.

**TO DISCUSS** should this replace the current behavior of exporting all children, should there be one button for each or we add a popup warning the user when only filtered data is exported?

**Proposed Solutions & Alternatives**
This can probably be achieved easily by using `entitySubrecord.recordsDataSource.data` for the `appExportData` directive in the `EntityListComponent`

**Comment by sleidig** [comment]
This point has come up again while answering questions of actual users. I do think the more intuitive (and useful/powerful) behavior is to export only the filter, visible data. (Of course including all pages of the pagination).

**Comment by TheSlimvReal** [comment]
Maybe also only export the columns that are currently shown.
