### ISSUE TITLE
date-range filter for Entity Lists

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1383]
For some entity lists (e.g. Notes, overview of all HistoricalObservation records, etc.) it would be useful as a user to define a custom date range for which results should be displayed. The UI could look similar to the period selector for our reporting module.

**Comment by TheSlimvReal** [comment]
Inspiration 
![Screenshot 2022-11-03 at 19 42 45](https://user-images.githubusercontent.com/33730997/199807677-cf00b840-1495-44ed-897d-a3ec47ce95ba.png)
