### ISSUE TITLE
integrate GoogleMaps/OSM to display Child and School locations

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#139]
*As a social worker I want to see the exact location of a family's house on a map in order to easily find them for home visits and to plan visits of nearby families together.*

**Objective**
Social workers are often keeping contact with dozens of families in a chaotic neighbourhood. Especially new staff members or those usually working with other families may not know all the houses. Finding an address by street and house number can be extremely difficult and in some slums no official address exists. A visual map with the locations will be very useful for planning and finding houses.

**Proposed Solutions & Alternatives**
* A map component display in a separate section of the child details that displays a pin for the home of that child. Also displaying other children's homes on that map can be helpful for orientation.
* The map component can also be displayed as a stand-alone global view to display all children's home locations and schools to get a global overview of the neighbourhood.
* To save a new location, putting a pin on the map probably is most feasible. Later it would be interesting to allow users to add a GPS location when using the application on a smartphone.
* Similar to Child locations, a map section can also be added to school details.

**Notes for Implementation:**
* Location probably should be saved as long/lat coordinates with each Child entity

-----

**User Stories**
- [x] add/edit geo-location to an entity through drag & drop functionality on a map
- [x] delete geo-location of an entity
- [x] visualize the geo-location of an entity on a map within its details view
- [x] visualize multiple entities with their location on a single map

**Comment by sleidig** [comment]
we should check out this: https://blog.angularindepth.com/google-maps-is-now-an-angular-component-821ec61d2a0

**Comment by TheSlimvReal** [comment]
What kind of map integration do you have in mind? Would this be just another section in the child/school details view where the map is centered on this child/school or do you think of a separate component that displays all children & schools?

**Comment by sleidig** [comment]
I updated the description with more details.

**Comment by TheSlimvReal** [comment]
I see the following tasks and potential free (and not GoogleMaps) solutions:

- [ ] Have a form field that allows to enter a normal address. Upon confirmation, the geo-location of this address is selected.
- - Free&public solution would be [nominatim](https://nominatim.org/). It comes with limited auto-complete support though.
- - A more professional but potentially costly option would be [locationIQ](https://locationiq.com/demo#autocomplete)
- [ ] Calculate distances between two geo-locations 
- - Use Law of Haversines or Spherical Law of Cosines to calculate distance in frontend ([examples](https://henry-rossiter.medium.com/calculating-distance-between-geographic-coordinates-with-javascript-5f3097b61898))
- [ ] (optional?) Display location(s) on a map
- - Use [Leaflet & OpenSteetMap (OSM)](https://www.digitalocean.com/community/tutorials/angular-angular-and-leaflet)
