### ISSUE TITLE
provide "age" for any date property

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1432]
e.g. also on school entities or others it would be useful to be able to use the "age" in the entity list

**Comment by TheSlimvReal** [comment]
Just displaying this with a component (e.g. `DisplayAgeComponent`) will make it not sortable/filtereable.

**Comment by sleidig** [comment]
maybe on the entity class we could use a custom "DateAndAge" object as property instead of a `date`. Then we can put the function to calculate age into that property instead of keeping it on the class itself.

**Comment by TheSlimvReal** [comment]
another solution would be together with the #1056.
We would have a generic `Person` class in the application which has the date of birth logic which can then be subtyped by any entity.
As this required a bigger chance first it could still be worth to go with the `DateAndAge` object first.
