### ISSUE TITLE
Allow custom date ranges for notes filter

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1448]
In the notes manager component (under *Notes*) there is a default filter which shows the notes from this week, the ones since last week and all the notes. This filter is hard coded and can only be enabled/disabled. 

This hard-coded filter should be extended with the option to create custom date ranges, e.g. last 7 days, last 30 days, this week, this month, ...
The functionality should be configurable through the `config-fix.ts`.
It probably makes sense to have a list of possible date ranges that should be available.

**Comment by sleidig** [comment]
this is somewhat related to #1383 - making a filter to select concrete from-to range available to be selected by users
