### ISSUE TITLE
Adapted Note UI for Meetings and Excursions

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#145]
The `Note` entity is also used to document a child's participation (or absence) in meetings. At the moment users create two Notes after a meeting: one linked to all the children who were present and one linked to all the children who were absent, each with an appropriate title. To make it easier to document and understand participation the UI should be extended:

- [x] Note categories "Guardians Meeting", "Children Meeting", "Excursion/Trip" can be selected and cause an automatic change of the NoteDetails UI
- [x] Note entity uses an array with 3 fields (`childId: string`, `present: boolean`, `remarks: string`) instead of simple `children: string[]` array. By default remarks is empty, present is true.
- [x] Meeting Notes have a table of linked children in addition to the selection list. When a child is selected from the list it is added to the table where the user can select whether the child was present/absent and if necessary write a short text remark related to that child.
- [x] In the Notes table of a Child, Notes of meeting categories are displayed in a different color than other notes and differently colored for a child who was absent or present.

**Comment by codingfabi** [comment]
Was this done with PR #154 ?
If so, can you close the issue?

**Comment by sleidig** [comment]
No, this is a different feature related to Notes and still open.
