### ISSUE TITLE
Improve text filter for dates

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1476]
**Describe the bug**
The text filter in the entity lists (children list, notes list, ...) does not work on date properties.

**To Reproduce**
1. Go to 'Note'
2. In 'Filter' enter '2022-'
3. All notes are hidden, even when this string equals what is shown in the table

**Expected behavior**
The filter should match with the string that is also displayed.

**Additional context**
For this the function `getReadableValue` in the file `value-accessor.ts` needs to be extended with a case for date formatting. The date formatting needs to be aligned with the locale of the user.

**Comment by amrendranath** [comment]
@TheSlimvReal I would like to work on this issue. Can you assign it to me?

**Comment by sleidig** [comment]
as we are introducing a dedicated date range filter (#1383), I would not focus on implementing this for the free text filter
