### ISSUE TITLE
`QueryService` function to get all participants of a `RecurringActivity`

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1482]
Children can be linked in two ways to a `RecurringActivity` either directly through the `participants` array, or indirectly through the `linkedGroups` and the active `ChildSchoolRelation` of that group.

In an export it can be useful to get all the children that are linked to an activity, as this will also be the children that appear when attendance is recorded. To allow this, we need a simple helper function which directly collects this information.

e.g.
```json
{
 "query": "RecurringActivity:toArray:getAllParticipants",
 "subQueries": [
  {
   "query": ".schoolId:toEntities(School).name",
   "label": "School Name"
  },
  {
   "query": ".childId:toEntities(Child).name",
   "label": "Child"
  }
 ]
}
```

The `getAllParticipants` function should have the following interface:

```javascript
getAllParticipants(activities: RecurringActivities): { schoolId: string, childId: string}[] {
  // code goes here
}
```
The `schoolId` should be left empty if the participant has been linked directly.

**Comment by sleidig** [comment]
Closing this as we are deprecating the QueryService, frontend-based reports in favor of the SQL-based Reporting API
