### ISSUE TITLE
Performance testing for CouchDB attachments

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1497]
- CouchDB raw performance (API)
- Performance in application (+UI)

**Comment by sleidig** [comment]
Edge cases to be tested:

- some file attachments of large size (100MB)
- 1000+ file attachments in db

**Comment by sleidig** [comment]
previously we had issues (but that was about syncing attachments in a pouchdb) https://github.com/Aam-Digital/helgo_db/issues/35
