### ISSUE TITLE
Comprehensive Technical Documentation and Decisions

### ISSUE THREAD

**Issue by fschoell** [Aam-Digital/ndb-core#15]
We should define a place and structure for our technical documentation. The Github Wiki is a possibility but it may be too restricted in functionality. Another possibility would be using Github Pages with some documentation generator like [Sphinx](http://www.sphinx-doc.org/en/stable/).

But way more important is that we start to document our technical design decisions. We had a discussion about the architectural pattern we use for the database mapping and how we handle the references for example. I think it's important that we document our decision and why we chose it. This eases up the implementation, makes the decision transparent for the future and helps new developers understanding the architecture. (I can't recall the decision we made for example, I would have to look it up in the code now and even there I wouldn't find the reasons for this decision)

I added a Wiki page for now until we decide how we do the technical documentation.

**Comment by sebastian-leidig** [comment]
The discussion about database mapping is documented somewhat detailed in the relevant issue #1 discussion. I like this as it keeps documentation simple and in one place only. But you may be right that this gets lost too easily and might not summarize decisions and reasons well.

**Comment by vlle1** [comment]
I consider this done. See #293.
new place for technical documentation: 
http://aam-digital.github.io/ndb-core/index.html
