### ISSUE TITLE
Small addition to edit text with autocomplete (get back to adding new entity)

### ISSUE THREAD

**Issue by christophscheuing** [Aam-Digital/ndb-core#1512]
Up to now the edit-text-with-autocomplete is only used for adding recurring activities directly from the school's details view.

After once having selected an entry from the autocomplete dropdown list, I can still modify the title field and thereby edit the title of the selected entity or select another entity offered in the autocomplete dropdown list. However there is no possibility – apart from discarding the popped up dialogue and reopening it – to get back to adding a new entity. I think that as a user I'd expect that by completely deleting the text in the title field I can discard the selected entity and get back to adding a new entity (or selecting one via the autocomplete dropdown list), i.e. the status of the dialogue when it was opened at the beginning.

Implementing this would take away the possibility to first select an entity via the autocomplete dropdown list and then completely change its title. However the edit-text-with-autocomplete seems to be the wrong place for doing so anyway. If I want to change the title of an existing entity, I should rather find it in the displayed list of existing entities and edit it from there.

**Comment by sleidig** [comment]
Good point. I think it might be good to make the title read-only there when it is an existing record being edited? That would also be a strong signal to the user that the current action is different from creating a new one. We could also add a small "x" button to remove the selected activity and start fresh.
