### ISSUE TITLE
Directly editing account information after creation

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1513]
**Describe the bug**
Editing a user account information after creating the user throws an error.

**To Reproduce**
1. (as admin) Go to 'users'
2. Create a new user
3. Go to 'security'
4. Add a email, roles and save
5. Edit email and/or roles and save again
6. See error

app tries to request https://accounts.aam-digital.net/account/undefined

**Expected behavior**
It should allow to edit the same information again without having to re-visit the page

**Comment by sleidig** [comment]
when I try to edit the security (e.g. roles), I actually do not even see a save button. Just "deactivate user" and "cancel",
