### ISSUE TITLE
use ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1586]
For components like Edit and Display components and entity block components we probably can switch to the less performance demanding on-push change detection. Should be tested (and maybe benchmarked) however.

**Comment by TheSlimvReal** [comment]
From now on, all new components should use `onPush`

**Comment by sleidig** [comment]
Closing this for now. We are considering to transition existing components to onPush change detection over time but the testing hasn't shown huge gains, so this is not an explicit priority/task.
