### ISSUE TITLE
mark required fields of Add-Monthly-Attendance form

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#160]
The `AddMonthAttendanceComponent` provides a form to easily enter attendance data in batch for a whole school or coaching center. The form should use proper Angular form annotations to show which fields are required and link the error message with these checks.

**Comment by sleidig** [comment]
user requests have been to allow saving an incomplete list of students as well. Maybe the required fields also have to be reconsidered

**Comment by codingfabi** [comment]
reconsideration:
if we want to store incomplete data sets, should we even have required files? or do you think, at least the name of a child should be required?

**Comment by sleidig** [comment]
The original consideration was that the user should add the complete data for a all students of a school in one go. Skipping students was not allowed as it is difficult to later understand which students' data is missing.
However, in practical use it turns out that sometimes data for a student is not available yet. In that case the user has to create an entry anyway in order to save the whole list. Which is even more confusing.

Generally, we should probably not force users into completing larger chunks of things together and give them flexibility.

---
In this case I would suggest a checkbox for each row (i.e. each student) to indicate whether this student's data will be saved or not. The checkbox is checked automatically when data is entered for that student but by default is unchecked. Maybe tooltips can make this understandable for the user.

**Comment by sleidig** [comment]
This functionality was removed with the new event attendance implementation and will be re-designed at a later stage
