### ISSUE TITLE
replace custom user-account component with the "normal" user view

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1622]
Clicking on the (hard-coded) "profile" button leads users to the user account component that allows to change the password but does not show any other details of the user entity. Also, as this is a custom component, the layout has some problems (scroll bars) that are fixed for the entity-details view. It would make sense to show users the same user view that admins see and reduce the custom code needed here. (if necessary, the password change logic could go into a component that does not include the tabbed interface but just those fields).

**Comment by sleidig** [comment]
@TheSlimvReal will this be worked upon as part of the work allowing accounts for different entity types? #2143

**Comment by TheSlimvReal** [comment]
Not necessarily yet. At the moment these views still serve a quite different purpose (managing other accounts vs managing the own account) so nothing to be changed about this yet. Not to sure how relevant it is though (besides the difficulty to distinguish the two by names)

**Comment by TheSlimvReal** [comment]
I think this is less and less practical. Especially when we now add the link to the entity to the `UserAccountComponent` we have another difference between those components. For now I do not see a practical way to combine these two components (the only overlap is the "email" field).
In the future we can rather check whether we can use Keycloaks account UI (`.../realms/{realm}/account`) which would come with all the features we would want there.  However that needs quite some styling.

**Comment by sleidig** [comment]
Agreed. With the split of the user entity from the account, the link we have now should be enough. Closing this
