### ISSUE TITLE
refactor dashboard widgets to build upon the generic dashboard-list-widget

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1632]
PR #1629 introduced a new generic component `DashboardListWidgetComponent` to make building of dashboard widgets easier. For example, that component automatically adds a paginator.
Most old widgets are not using the new component yet. Similar to ImportantNotesDashboard other components should also use the DashboardListWidgetComponent to simplify their code.

- go through all components that are Dashboard Widgets (they will at least have "dashboard" in their name) and list those that are not using `<app-dashboard-list-widget>` in their template yet
- refactor these components, using the <app-dashboard-list-widget> in the html template should allow us to remove some things like mat-paginator because it is automatically included from <app-dashboard-list-widget>

**Comment by sleidig** [comment]
Step by step:
1. List all components still using the app-dashboard-widget (not the new app-dashboard-list-widget) here in the GitHub issue.
2. Change in the html to app-dashboard-list-widget
3. Remove isLoading and title that are not needed anymore
4. add [entries] to pass the array of items to be listed
5. remove from the html inside the code for pagination, etc. - only keep the <table>
6. from the component.ts remove code of the pagination, etc.

**Comment by sadaf895** [comment]
1.Attendance-week-dashboard.
2.Notes-dashboard.
3.Progress dashboard
