### ISSUE TITLE
User-editable dropdown options (configurable-enum)

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1642]
*As a manager I want to quickly add new options for a dropdown field without need for technical support when our project structure changes a bit.*

Requirements:
- [x] allow typing for dropdowns to narrow results
- [x] provide option to create new item (and clearly distinguish that visually from selecting an existing option, consider asking for confirmation to avoid unintended entries being created?)
- [x] provide UI to edit (the label of) an entry
- [x] delete an entry (and provide logic to ensure the delete value is not used anywhere)
- [x] enforce permissions that control adding enum options

**Comment by sleidig** [comment]
Thoughts about the UI:
![image](https://user-images.githubusercontent.com/1682541/212355604-d57e5bf1-1ba9-4077-84f7-e16b4cbb42a6.png)

**Comment by TheSlimvReal** [comment]
- [ ] (optional) items can be re-ordered
