### ISSUE TITLE
Month select component

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1666]
At the moment, it is only possible to select a full date in the `EditDateComponent`. In some cases, users only want to select a month, without a day of the month. A new component should be added that supports this. This component should then be the default edit component for the `monthEntitySchemaDatatype`. Maybe the datatype format also has to be adjusted.

Angular Material has a guide for a [year and month picker](https://material.angular.io/components/datepicker/overview#watching-the-views-for-changes-on-selected-years-and-months)

**Comment by sleidig** [comment]
this is closely related to #1657
