### ISSUE TITLE
customer support account without a user entity

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1685]
At the moment we often keep an admin account for customer support and setup in client instances. It would be good if we have a different (securely protected, maybe by a pin to be shared by the client) access to systems without having a "real" account.

Remarks:
- related: prevent such sessions from being tracked in matomo usage analytics: #1675 
- we currently use a user account created in keycloak which does not have a User entity. This works fairly well, as the users of the system do not have an "AamSupport" user record visibly floating around their system.

**Comment by sleidig** [comment]
This will be closed as part of #2143 .

@TheSlimvReal is it still necessary to define the Keycloak "exact_username" attribute and set it empty - or can that be missing completely now?

**Comment by TheSlimvReal** [comment]
@sleidig No, defining `exact_username` its not required anymore.

**Comment by TheSlimvReal** [comment]
Lets only close this once the PR is actually merged which implements this.
