### ISSUE TITLE
Allow column headers in RowDetails

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1687]
Some clients have very complex records with many fields. The popup form (RowDetailsComponent) also needs to support headers similar to the EntityDetails form to make this manageable.

**Comment by TheSlimvReal** [comment]
Maybe use #1695

**Comment by sleidig** [comment]
With PR #2304 it is possible now to open a dialog popup with any component, including EntityDetailsComponent (or FormComponent). So this is mostly just a question of config now
