### ISSUE TITLE
public forms are empty in incognito mode

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1694]
If someone opens the public form in incognito / private browsing mode the form is displayed without any fields. If we can't easily make the form work in that mode we should try to display a message to users for feedback.

**Comment by TheSlimvReal** [comment]
Seems to be a permission issue. With #1661 unauthenticated users most likely also need read access to the `ConfigurableForm` entity

**Comment by TheSlimvReal** [comment]
Still seems to be an issue on direct entry in demo mode
