### ISSUE TITLE
Allow navigation to details view instead of popup in related-entities and related-activities subrecords

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1695]
For some related entity tables (e.g. recurring activities of a school; some custom, complex survey details) the user should be navigated to the fullscreen details few of a record when clicking on the row instead of seeing a popup. Make this configurable.

**Comment by sleidig** [comment]
... we have a problem to implement this because the `createNewRecordFactory` needs to create and pass a temporary entity:
- the logic for new record default fields is in the list component (we might be able to switch this into becoming config of the "entity" maybe)
- this logic can make use of the "relatedEntity" and its properties. there wouldn't be any reference back to this in our usual approach of opening a new details view ...

**Comment by TheSlimvReal** [comment]
Maybe offer link in `RowDetailsComponent` to go to `EntityDetailsComponent`
