### ISSUE TITLE
UserAccount password change

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#17]
The user needs a simple "user account" page where she can change her password (and maybe in the future edit other account details).
The same component could also be used for admins to view or edit another user's account or create a new account.

**Attention: Users are not just normal Entity instances**
We currently have a slightly complex concept where a user exists as an Entity in the normal database and _additionally_ as a CouchDB user object (int the _users db). Passwords need to be changed in both objects in parallel!

- see https://github.com/Aam-Digital/ndb-core/issues/272#issuecomment-494941923 for more details
- also refer to the [add-user script](https://github.com/Aam-Digital/ndb-setup/blob/master/add-user.js) which currently does this job outside of the UI
- we should also consider changing the architecture around user accounts overall (see #272)

-------
**After revising the technical requirements, the steps for implementation are as follows**
(copied from @TheSlimvReal below):

- [ ] Create `UserAccountService`
- [ ] Create `ChangePassword` function
- [ ] `GET` request to `/db/_user/org.couchdb.user:<user>` with username and password in authorization header to get user data 
- [ ] add password field to user object with the unencrypted password
- [ ] `PUT` request to `/db/_user/org.couchdb.user:<user>` with new object and username and old password authorization header
- [ ] Update user object in local database

**Comment by aankitkumar31** [comment]
develop UserAccount View

**Comment by Lorsbyjm** [comment]
check branch change pw

**Comment by sleidig** [comment]
basic user account view is done. However, backend work to properly change to password (which is linked between local database and remote server) is pending

**Comment by codingfabi** [comment]
a user view is already existing. only functionality to change password is missing.

**Comment by codingfabi** [comment]
@sleidig could u create a test user for me so i can test the password change feature? i dont want to mess up the only user that we have...

**Comment by sleidig** [comment]
Another user is available now:
Username: Tester
Password: pass

**Comment by liwde** [comment]
Work on the improved session continues and the interface supports an "offline" state that can be read and listened to. This way we can make sure the password may only be changed when the user is online.

However, currently the offline state is not really set inside the improved session. I'm currently focusing on feature parity, but after this we can look into how to set the online/offline state.

**Comment by codingfabi** [comment]
What is the status on this? @liwde can you give a quick update if this is possible to do now with the new session implemented?

**Comment by TheSlimvReal** [comment]
- [ ] Create `UserAccountService`
- [ ] Create `ChangePassword` function
- [ ] `GET` request to `/db/_user/org.couchdb.user:<user>` with 
username and password in authorization header to get  user data 
- [ ] `PUT` request to `/db/_user/org.couchdb.user:<user>` with
