### ISSUE TITLE
Record attendance list should exclude "inactive" activities

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1707]
**Describe the bug**
Recurring Activities can be marked archived through a profile property (e.g. `inactive`), which will make sure the `isActive` flag is false and the record can be hidden from various lists. The "Record Attendance" roll call setup screen should also respect this and exclude any isActive === false activities.

**Comment by TheSlimvReal** [comment]
Maybe with tooltip on inactive checkbox in entity class
