### ISSUE TITLE
`groupBy` reports should use human-readable label

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1724]
In the `ReportRowComponent` the value description for missing values is `without gender` or `not active`. However the `gender` and `active` are the property IDs instead of the actual label of this property. This should be changed to the human readable label.

**Comment by TheSlimvReal** [comment]
See https://github.com/Aam-Digital/ndb-core/blob/master/src/app/features/reporting/report-row.ts#L27

**Comment by sleidig** [comment]
Also (and a bit more advanced), when grouping by a referenced entityId (e.g. the school a child is linked to), groupBy needs access to a sub-property of the grouped property to give a sensible displaying.

@TheSlimvReal , not possible yet, is it?

**Comment by TheSlimvReal** [comment]
@sleidig no, this is also not possible with the JSON queries.

**Comment by sleidig** [comment]
Closing this, as we are deprecating frontend-based reports in favor of the SQL-based Reporting API.
