### ISSUE TITLE
Set up CouchDB server to provide _bulk_get

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#175]
PouchDB is giving a note in the console 

> POST https://couchdb.SERVER.com/DB_NAME/_bulk_get?revs=true&latest=true 400 (Bad Request)
> The above 400 is totally normal. PouchDB is just detecting if the remote supports the _bulk_get API.

`_bulk_get` is supposed to speed up replication of the database significantly, which might help solve the long initial loading times for us after first login (https://pouchdb.com/2015/10/06/pouchdb-5.0.0-five-years-of-pouchdb.html)

I couldn't find any documentation on how to make the CouchDB server support bulk_get, however ...

**Comment by codingfabi** [comment]
This looks quiet familiar, but only quiet. Normaly when im working with pouchDB, i get errors of this kind:

_The above 400 is totally normal. PouchDB is just detecting if the remote supports the _bulk_get API._

Which PouchDB and CouchDB Versions are we using?
According to this discussion: https://github.com/pouchdb/pouchdb/issues/3424 it should work as far as i know.
its hard to help with this issue without any real insights of the server, do you have any more infos?

**Comment by sleidig** [comment]
It looks like nowadays the `_bulk` api requests are actually accepted from our CouchDB server, so this ticket can probably be closed.
