### ISSUE TITLE
store import settings (column mappings, etc) in database for easy reuse

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1771]
The object that can currently be downloaded at the end of an import should be saved to the database instead.

This should give the following benefits:

- Have a history of imports
- Select a historical import to use the configuration from there
- Undo a historical import
- All users have access to this instead of just the person that did the import

Maybe the transaction ID can also be replaced by just saving the IDs of the imported data to later remove that data again.

UNDO
- what happens with references (`ChildSchoolRelations`, `RecurringActivities`) that are created during import
- what happens with edited entities (`doc._rev > 2-...`)

**Comment by sleidig** [comment]
implemented in #1916
