### ISSUE TITLE
preview all data before import

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1772]
Before the final import is saved to the database a preview should show all the parsed data. For this the data should be parsed to entities and then a popup with an entity subrecord table can be used.

In this table it should also be possible to make slight adjustments (e.g. using the entity subrecord edit row functionality).

Only after the user approves this, the final import is done.

The same should probably also happen when related entities are created/edited (for school/activity membership).

**Comment by TheSlimvReal** [comment]
This could also be a real time view where the mapping results are directly shown in a table below.

**Comment by sleidig** [comment]
implemented in #1916
