### ISSUE TITLE
Properly Declare Imports in Modules

### ISSUE THREAD

**Issue by liwde** [Aam-Digital/ndb-core#180]
Currently, the AppModule has lots of `imports`. These are not necessarily used by the AppModule itself, but rather Modules it imports. These, however, do not always properly declare their imports. The SchoolsModule for example uses the EntityMapperService, but never declares the import. Currently this works, because the EntityModule is imported somewhere else - we should clean this up!

**Comment by sleidig** [comment]
also, to make things more readable modules re-exporting a set of related modules (i.e. a MatModule summarizing all angular material modules) would be helpful (https://angular.io/guide/ngmodule-faq#can-i-re-export-classes-and-modules)
