### ISSUE TITLE
Contact in India

### ISSUE THREAD

**Issue by Lorsbyjm** [Aam-Digital/ndb-core#183]
For maintenance and language support it would be nice to work together with locals. Maybe there is an unisversity near by where students want to support us.

**Comment by codingfabi** [comment]
Contact to some users from HELGO would be nice aswell

**Comment by sleidig** [comment]
Also, if you have a clear idea of what kind of collaboration you would like, I may be able to put you in touch with Indian college students. Don't underestimate the effort and need for regular interaction however, to make this work.
