### ISSUE TITLE
Location input should allow to manually extends the address 

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1844]
The location input only allows to select an existing address. 

Sometimes it might be necessary to extend this address with additional information (while still keeping the coordinates) e.g. to save street number 6b instead of just 6.

Problems / aspects related to this:
- import of address may loose information (if the address cannot be mapped, it doesn't get imported at all)
- additional address details (like floor, building number, etc.) cannot be saved
- the entered address is reformated (e.g. showing house number before the street name) and displayed differently from what the user typed - which can cause confusion.
- Address field should be a long text field to display the details fully (?)

---
_Als Projektkoordinator:in muss ich manchmal Zusatzinformationen zu einer Adresse angeben oder eine Haus-/Wohnungsnummer speichern, die nicht im offiziellen Adress-Register vorhanden ist (das für die Kartenfunktion abgefragt wird)._

**To implement:**
- [x] datatype: change `LocationDatatype`
  - [x] store "raw address" string in addition to the location lookup object `{ locationText: string; geoLocation: GeoResult }`
  - [x] migration function to provide backward compatibility
- [x] UI:
  - [x] `ViewLocationComponent`: display locationText (+ icon if geo available) 
  - [x] `EditLocationComponent`: textbox for custom location text + button to "locate on map" (which triggers search, allows to select geo-result); From lookup popup, can copy address back into custom address - or otherwise system will just display "[selected on map]"
- [x] Import:
  - [x] module saves the exact address string imported in the locationText, even if the address cannot be found and mapped on the location API. (currently invalid address details are not imported at all)

**Comment by sleidig** [comment]
We would need to store (and display) an "extraAddress" text in addition to the lookup GeoResult. This leads to a number of variations to consider regarding UX. We might either display two form fields or smartly combine things into one (if we can figure out a good way for that).

User stories & edge cases (assuming two strings: _address_ and _extraAddress_):
- [x] _address_ = lookup location (existing cases to set / edit); no additional extra_address defined
- [ ] set _extraAddress_ to non-existing location
- [ ] edit _extraAddress_ from non-existing to existing location
- [ ] edit _address_ from existing location to non-existing location

---
The easiest implementation would be to just have an independent additional text field:

> Address: _..address.._ [map icon]
> Additional address details: _..extraAddress.._ [?]
> 
> [?] tooltip --> Make sure to enter and select the full address in the field above. The additional details can hold details like apartment number or navigation instructions but will not update the map visualization or the address field.

**Comment by sleidig** [comment]
This has similarities to adding an "other" text input for configurable-enum (dropdown) fields: #1677
Maybe we can design a generic approach covering both.
