### ISSUE TITLE
add new option from enum popup window

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1872]
As the dialog is offering to rename and delete options already, it would be helpful to also have the option to add completely new options not only from the dropdown field but also in its option edit dialog shown when clicking the tool icon.

-----
### Implementation details:
- use `npm run storybook` to test and improve the component "Core / Entities / Edit Properties / Enum Dropdown / Primary"

- Component / template to be extended: `ConfigureEnumPopupComponent` 
(add a button to "add new option" between the last existing field and the close button)
![image](https://github.com/Aam-Digital/ndb-core/assets/1682541/16a369e6-40fa-4d19-adef-3ea56d41a867)

- current logic to add a new value to the options in `EnumDropdownComponent`: move this to `ConfigurableEnumService` and reuse
https://github.com/Aam-Digital/ndb-core/blob/8db14d8c0ca4a9412f853700eebfc1bf814dfa44/src/app/core/configurable-enum/enum-dropdown/enum-dropdown.component.ts#L78-L83

**Comment by TheSlimvReal** [comment]
Seems to be more necessary than I expected. A lot of people only find the rename option but don't realise that you have to enter something in order to add a new option.
