### ISSUE TITLE
API endpoint for accessing reporting data

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1887]
To integrate Aam Digital with other systems like TolaData's monitoring & evaluation platform, data should be accessible for external systems through a secure API.

Currently we achieve a "manual integration" by configuring custom reports, have users download the csv file of a report from Aam Digital and upload that file in the other system. The idea is to make the same data available not only as a csv download but also through a server API automatically.

also see https://docs.google.com/document/d/1kXhP01F8EvHBAPNHqQhWUqJYSJBEut3a02MIYUrGkF8/edit#

**Comment by sleidig** [comment]
@TheSlimvReal does the current API already support access via some kind of API token?

**Comment by TheSlimvReal** [comment]
@sleidig No, this still needs to be added

**Comment by sleidig** [comment]
see https://github.com/Aam-Digital/aam-services/issues/11
