### ISSUE TITLE
Cancel button should not be transparent

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1917]
The `cancel` button when editing a form in a entity details page currently is transparent and therefore especially on mobile screens not perfectly visible.

<img width="316" alt="Screenshot 2023-07-03 at 16 27 15" src="https://github.com/Aam-Digital/ndb-core/assets/33730997/195205d2-9fa9-4940-a8a5-f7f7e20747d4">

What would be best is to keep the same style but make the button have a solid background color that is the same as the general background color.

**Comment by bubu2323** [comment]
if you want you can assign it to me and I can work on it

**Comment by TheSlimvReal** [comment]
@bubu2323 done and thanks for offering. Let me know if you need any further help. The buttons can be found in the [FormComponent](https://github.com/Aam-Digital/ndb-core/tree/master/src/app/core/entity-components/entity-details/form)

**Comment by TheSlimvReal** [comment]
@tarunsamanta2k20 done. Looking forward to reviewing your PR and see the comment above for the best location to make the required chagnes.

**Comment by TheSlimvReal** [comment]
Dear @tarunsamanta2k20,
thanks for investigating this. I think you should be able to set a background color with plain CSS on the button element. 
You can find the color which is used for the app background [here](https://github.com/Aam-Digital/ndb-core/blob/master/src/app/core/ui/ui/ui.component.scss).

<img width="1384" alt="Screenshot 2023-07-18 at 12 39 54" src="https://github.com/Aam-Digital/ndb-core/assets/33730997/e0f744a4-53f8-4b7a-97ca-d35d00958d98">
