### ISSUE TITLE
Allow date-range filter to be cleared (and show records of any date)

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1967]
It is currently not possible to clear the filter of a selected date range. Users should be able to reset that and show all records of the list without filtering by date, if they want to.

We could look at this even more generically also: Allowing to clear any filter. Currently, we add an "All" option to dropdown filters automatically to allow all results to show.

**Comment by christophscheuing** [comment]
UI wise there could be an "All" option in the panel of de date range popup. But we should also enable the "All" option by clearing the dates in the text input field.

And we might also introduce the possibility of only entering only one of the two date borders in the input field.

All of this should also be reflected in the URL and also work the other way round, meaning that changing the URL should change the filter setting in the adequate way.
