### ISSUE TITLE
Generalize (base) UI components

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#199]
To avoid code duplication and duplicate work, we should look into common UI components and generalize them.
We can look into different approaches: 

- develop an abstract base class to be extended for different use cases
- develop a generic component that may accept some config variable to adapt it to slightly different use cases (e.g. like `EntitySubrecordComponent`, `FilterSelection<T>`)

This will also help us to make more of the UI user-configurable through the UI itself, rather than specifically hard-coding each screen.

Related to this: #6 

## Components to be generalized:
- [x] Children list filters (filter children by center, status, ...); to be reused in attendance manager and other places
- [ ] Entity Select Form Element (we have `ChildSelectComponent` but this should be generalized into an "EntitySelectComponent" to reuse it for users, schools, etc.)
- [ ] Entity Block Component (i.e. generalization of `ChildBlockComponent`, `SchoolBlockComponent`)
- [x] List Component (i.e. generalization of `ChildListComponent`, `SchoolListComponent`)
- [x] Details Component (i.e. generalization of `ChildDetailsComponent`, `SchoolDetailsComponent`)

**Comment by vlle1** [comment]
the selection menu (mat-form field / mat-button-toggle-group) of html in notes-manager.component, attendance-manager.component is redunant. (add this to Components to be generalized)

**Comment by sleidig** [comment]
most important components have been refactored and generalized in #550 .
Closing this - new issues can be opened for specific individual components.
