### ISSUE TITLE
CSP warnings in real operation

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1999]
After deploying the CSP (report-only), some content is still triggering warnings and not properly whitelisted in our default CSP:

- Refused to load the image 'blob:URL'
- Fetch API cannot load https://o167951.ingest.sentry.io/api/1242399/security/. Request mode is "no-cors" but the redirect mode is not "follow".

**Comment by TheSlimvReal** [comment]
One problem is that the `index.html` script hash has not been correctly updated. How can this be done?

**Comment by sleidig** [comment]
I documented this here in den Developer Docs "Security" Concept (happy for suggestions about a better place): https://aam-digital.github.io/ndb-core/documentation/additional-documentation/concepts/security.html

**Comment by TheSlimvReal** [comment]
The instructions dont seem to work on all browsers (this is from Chrome on Mac, Safari seems to show even less info)
<img width="619" alt="Screenshot 2024-01-22 at 09 20 49" src="https://github.com/Aam-Digital/ndb-core/assets/33730997/214cb69d-ca26-44a0-8952-610c2a18632b">
