### ISSUE TITLE
Attendence Manager list structuring

### ISSUE THREAD

**Issue by codingfabi** [Aam-Digital/ndb-core#201]
So far, in the attendence list every child has two entries in the table, because there is one entry for the schooling attendance and one for the coaching.
I dont have a concrete idea either but maybe we should find a way to show these two types of attendance without showing to entries for the same child

**Comment by sleidig** [comment]
I started initially with one row per child and the two types of attendance in two lines within the same row. However, then sorting by attendance will not be possible (by which of the two values should be sorted) and there was a lot of code duplication for the two parts. In the long term we should get away from hard coding exactly two types of attendance anyway - there may be projects with just one type of attendance or even with more than two.

The solution now looks a little weird but has those usability advantages. Planned but not implemented yet is a filter to only show coaching/school attendance.

**Comment by sleidig** [comment]
Closing as this has been lying idle for a long time and current implementation is usable.
