### ISSUE TITLE
Language is locked in to "English" because SiteSettings is loaded only after first initialization

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2014]
**Describe the bug**
It seems everyone is locked to English language of the app currently, after we transitioned to the separate SiteSettings object.

**To Reproduce**
1. Clear App data
2. Reload
3. Initial Login Screen is English (has that previously been the defined language on first load?)
4. After login, the SiteSettings are loaded - but probably the app already stored the initial language, a change does not take place if siteSettings define a different language

**Comment by TheSlimvReal** [comment]
Not a but in the code but in the migration script. It used "language" instead of "defaultLanguage".
