### ISSUE TITLE
User roles sometimes not accessible because auth with backend expired

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2044]
**Describe the bug**
Users sometimes only see an empty dropdown for user roles. This seems to happen when the remote authentication with the account-backend expires but the user is still logged in in the frontend. Logging out and re-login resolves the issue, but currently there also is no user feedback at all about what went wrong.

**Comment by sleidig** [comment]
@TheSlimvReal with the new login system (PR #1990): If the remote connection fails (for syncing or loading roles on the user account component) while the user is logged in: Are we handling that in any way? Can/Should we send the user to remote login again?

**Comment by TheSlimvReal** [comment]
No, in this regards nothing is changed. It still behaves as before.
