### ISSUE TITLE
"Reset Application" does not remove local db anymore / if not logged in

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2060]
**Describe the bug**
The Support Screen button to "Reset Application" does not work anymore. The browser indexeddb remains unchanged when visiting that screen without being logged in. Therefore it cannot be used to recover from issues where the user can't login anymore.

**To Reproduce**
1. Open an instance in "synced" mode (with persisted local db), e.g. https://demo3.aam-digital.com
2. Login, sync, ...
3. Logout
4. Navigate to the support page through the browser URL (e.g. https://demo3.aam-digital.com/support)
5. Click "Reset Application"
6. Checking in the browser console, you see that the indexeddbs are still filled

**Expected behavior**
Should remove all indexeddbs, resetting the app overall for any user on this device.

**Comment by TheSlimvReal** [comment]
This is because the username is needed in order to know which db to reset. An alternative approach would be to delete all indexed-dbs

**Comment by sleidig** [comment]
In my opinion we should delete all indexedDBs (at least when not logged in)
