### ISSUE TITLE
Migrate configs

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#2066]
This is a collection issue to collect potential places where it would make sense to migrate the config. Once we do a migration, all of these should be included.

- [ ] `EntityListComponent` rename property `columnGroups` to `columnGroupsConfig` and apply the same to the config property and the interface `EntityListConfig` (see [comment](https://github.com/Aam-Digital/ndb-core/pull/2064#discussion_r1386219013))
- [x] Align `NavigationMenuConfig` with `MenuItem` interface. Currently one uses `name` and the other uses `label`. The `DashboardShortcutWidgets` already uses the `MenuItem` interface.
- [x] Add subproperty for `HistoricalDataComponent` (see #2187)

### To discuss
- switch the config model a bit: one config doc per entity type? Would allow more useful typing of the Config entity also and group things in a useful way:
```
class Config extends Entity {
  @DatabaseField() entitySchema: EntitySchema;
  @DatabaseField() viewDetails: EntityDetailsConfig;
  @DatabaseField() viewList: EntityListConfig;
}
```

**Comment by sleidig** [comment]
moved the last remaining config migration point to the related Admin UI ticket: #2067

Let's close this and open new individual issues where needed. With the ConfigService migration function it has become fairly easy to just implement an on-the-fly migration also.
