### ISSUE TITLE
Generalized DialogViewComponent wrapper to display forms in popup

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2069]
We repeatedly need similar logic when displaying forms in a dialog/popup. To ensure the UX is consistent and make implementations simpler, a generic wrapper component that helps to display any component as a dialog would be useful.
Similar to the `RoutedViewComponent`, this new `DialogViewComponent` could allow us to implement the actual functionalities in components that only use `@Input()` and `@Output()` properties - which can then be used in both routed and dialog wrapped views.

Common functionality for all dialog forms should be:
- "x" (top right) to close the dialog
- confirmation message before closing, when changes would be discarded
- save + cancel button
- save process that marks all fields as dirty and check if form is valid (and aborts the saving if invalid)

![image](https://github.com/Aam-Digital/ndb-core/assets/1682541/e4bdb64f-5ba8-46e5-933b-ab149dda84c8)
[[source](https://docs.google.com/presentation/d/1g5970eYMJ8vdklWA_q59AyctxlVMrN-pLGa8X-dUdIk/edit#slide=id.p)]

---
concrete use cases / samples:
- [x] allow NoteDetails to be opened via RoutedViewComponent
- [x] allow EntityDetails to be opened via FormDialogService

**Comment by TheSlimvReal** [comment]
If you are talking about forms, isn't `FormDialogService.openFormPopup()` allowing to easily create these forms with the requirements you describe?

**Comment by sleidig** [comment]
> If you are talking about forms, isn't `FormDialogService.openFormPopup()` allowing to easily create these forms with the requirements you describe?

Yes and no. It does, but any Component you pass in as a parameter still needs to handle a lot of common stuff. e.g. both RowDetailsComponent and NoteDetailsComponent need to inject MAT_DIALOG_DATA (and therefore can't be used as a "routed view"). And both need to add standard stuff like the app-dialog-close ("x" icon), although we have encapsulated that nicely in a component that just needs to be added to the template.

In the long run, I would love to have components like NoteDetailsComponent (so that would probably include also the generic EntityDetailsComponent) that can be used both in dialogs and in main (routed) views. The biggest challenge there is probably how/where we handle the save buttons+actions.
