### ISSUE TITLE
Bring back the Back Button

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#208]
Most users are currently using the app in fullscreen mode with browser controls hidden. Therefore our UI needs to have its own back button in addition to the browser buttons that can be used to go to the previous screen.

**Comment by codingfabi** [comment]
Maybe we could show the application's back button only on fullscreen mode? 
Because i think it could harm the UX if you have to choose betweeen two buttons that do exactly the same...

**Comment by sleidig** [comment]
The feature is mostly needed navigating from a Details page back to a (filtered) List page. Maybe we integrate it into the UI explicitly only on the Details pages?
