### ISSUE TITLE
Add permissions to dashboard

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#2122]
Currently all users see the whole dashboard even if they might not even have access to the entities which are required to the dashboard widgets to work or they might not be able to visit the routes which are mentioned in the shortcuts widget.

The app should automatically detect which widgets the user cannot use/view and disable them, based on the route permissions or entity permissions.

**Comment by sleidig** [comment]
Shall we try to merge the two permissions logics (operations on entities + roles to access a route)? For the menu entry to the setup wizard I am struggling with that a bit

**Comment by sleidig** [comment]
related / overlapping with https://github.com/Aam-Digital/ndb-core/issues/1552
