### ISSUE TITLE
child photos not showing anymore

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#213]

**Comment by codingfabi** [comment]
Can you provide a screenshot, error message or anythin? cant really recreate this problem with the demo database.

**Comment by sleidig** [comment]
To recreate:

1. create a folder `src/assets/child-photos` and an image `XYZ.jpg` inside it
2. change the projectNumber of a child to `XYZ`

Expected outcome: the child photo src is set to `XYZ.jpg` and the picture is displayed

Actual outcome: the child photo src is still the default "assets/child.png"

**Comment by RichardNutt** [comment]
Note: If you provide photos for existing children (eg. `/assets/child-photos/1.jpg`) it will display them at first. If you change the projectNumber to something else (`1` to `42`) and then revert the change (back to `1`) it won't display the old image, even though it was once loaded.

**Comment by sleidig** [comment]
@RichardNutt: What's the status on this, displaying individual photos?

I tried again recently and still can't get images to be displayed at all. As this is a nice and very visible feature, the users have asked about a fix for this a couple of times already ;-)
