### ISSUE TITLE
[Setup wizard] Edit entity details issues

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#2130]
- [x] Drag and drop on the whole field, not just the small button
- [x] When editing in sidebar e.g. the label is not updated in the sidebar
- [x] When editing in the sidebar the elements suddenly change the order (I think sorted by field ID)
- [x] Toast "Config:CONFIG_ENTITY updated" is a bit technical. We might need a label for that. Although then that would probably mark the entity as non-technical and also show it in other scenarios, e.g. when allowing to link a relation?
- ~3 dot menu is still in background when entering admin mode (it can even be clicked by scrolling a little)~

**Comment by sleidig** [comment]
Thanks for reporting these! I'll look into that

**Comment by sleidig** [comment]
I couldn't replicate (3) and (5). Can you give me more details, @TheSlimvReal or @christophscheuing ?

**Comment by TheSlimvReal** [comment]
1: Move 'name' field to bottom of sidebar -> click edit on 'name' -> click 'save' -> see 'name' is suddenly at top
2: @christophscheuing can you still reproduce it? Somehow for me the 'save' and 'cancel' buttons don't stick to the top anymore

**Comment by christophscheuing** [comment]
> 2: @christophscheuing can you still reproduce it? Somehow for me the 'save' and 'cancel' buttons don't stick to the top anymore

Unfortunately I don't quite remember how we did that the other day and I'm not able to reproduce it at the moment. But I'll keep that in mind and let you know as soon as this behavior occurs again.
