### ISSUE TITLE
enable automatic change detection support for async ViewDirective sub classes  

### ISSUE THREAD

**Issue by tomwwinter** [Aam-Digital/ndb-core#2153]
As a *developer* I want to be able to use the default angular change detection experience without the need of manually mark components manually for change detection check.

Currently it is not possible to rely on the change detection in sub classes from `ViewDirective`, when the `ngOnChanges()` method is loading data asynchronous. Instead the developer must call the `ChangeDetectorRef.markForCheck()` manually.

**Proposed Solutions & Alternatives**
Find a solution that makes the manual triggering obsolete --> analyse necessary

**Comment by TheSlimvReal** [comment]
What we can do is `await` the function call of `ngOnChanges` in our `DynamicComponentDirective` [here](https://github.com/Aam-Digital/ndb-core/blob/master/src/app/core/config/dynamic-components/dynamic-component.directive.ts#L94).

**Comment by tomwwinter** [comment]
So it would be a one liner? Then we should do it right away, shouldn't we?

**Comment by TheSlimvReal** [comment]
Yes, and maybe check where we can then remove the custom change detection trigger.

**Comment by tomwwinter** [comment]
@sleidig Could be the case, if somehow the cd tree is not build correctly, i think. But would also mean, that we will have more (unnecessary) refreshes...

**Comment by sleidig** [comment]
This has been resolved by the mentioned changes of removing onPush strategy from `EntityFieldViewComponent`
