### ISSUE TITLE
Use ChildSchoolRelations instead of SchoolID

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#216]
Currently, we have a SchoolId tag at each child to indicate, which school it is visiting. We also have the ChildSchoolRelations, which store information, on which child visited which school for which period of time. Now we need to replace all usages of the SchoolId tag with the usage of the child school relations, so we only store the information of the attended school at one place.
When this is done, we need to port the old data to the new data model.

**Comment by TheSlimvReal** [comment]
There is another problem I ran into. Currently it's fairly easy to access the school's name from a child object, because it's just saved there. But if we now have the ChildSchoolRelation which will get us to the school object, where du we save that school object? For the moment I created extra classes that hold a child, a school and the relation object. This is needed, because in the child-list-component, we need the child object, the class (relation) and school name (school). Is there maybe a cleaner way to go?

**Comment by TheSlimvReal** [comment]
I pushed the current status on the branch ["child_school_relation_impl"](https://github.com/NGO-DB/ndb-core/tree/child_school_relation_impl) but I dont want to go much further till this questions are answered.

**Comment by sleidig** [comment]
We could add to `EntityMapper` and when loading a Child entity, immediately also load the current School entity and save that reference to the School object in an attribute like `Child.currentSchool: School` (same goes for the current class/grade, which will often be needed.
Then before saving the Child entity back to the database, we probably have to delete those references to avoid bloating the database.

Would be awesome if we could just save all related objects as references, like `Child.previousSchoolEnrollments: ChildSchoolRelation[]` and do lazy loading - i.e. only get the objects from the database once they are required. But that's maybe getting us in over our heads?

Once again, related to #108 (relational-pouch)

**Comment by sleidig** [comment]
> There is another problem I ran into. Currently it's fairly easy to access the school's name from a child object, because it's just saved there.

Actually we only have the schoolId, not the name itself in the Child currently. But that is mostly to keep writing to the database simple, for convenience maybe we should save object references (see my comment above)

> But if we now have the ChildSchoolRelation which will get us to the school object, where du we save that school object? For the moment I created extra classes that hold a child, a school and the relation object. This is needed, because in the child-list-component, we need the child object, the class (relation) and school name (school). Is there maybe a cleaner way to go?

Isn't ChildSchoolRelation already that class, holding the combined information? Maybe here also the EntityMapper should add the object references during runtime. Or you can use the IDs in ChildSchoolRelation similar to how now the Child.schoolId is used?

**Comment by TheSlimvReal** [comment]
> Isn't ChildSchoolRelation already that class, holding the combined information? Maybe here also the EntityMapper should add the object references during runtime. Or you can use the IDs in ChildSchoolRelation similar to how now the Child.schoolId is used?

The ChildSchoolRelation holds the ChildID and the SchoolID, but you still need to fetch the child and the school to get their names/infos. For views like the children list it wouldn't be very effective to always load them from the database.

**Comment by sleidig** [comment]
Yes, agreed. Although that is what we are still doing currently.

I think this loading of (close) relations should move into the `EntityMapperService` and add references to the Entities. I am creating a new issue for this topic: #228

**Comment by liwde** [comment]
I think we are facing a few problems here when we try to lazy-load

1. **Async Bindings to the View:** When we call e.g. `child.getSchool()` (and this method internally handles using the ChildSchoolRelation to get the current school), this would still be an asynchronous operation. Is it possible to bind to the View like this: `(await child.getSchool()).name`? After the first request, we could add some caching here, but the interface would still be async.
2. **Entities do not know about the EntityMapper:** Currently, Entities are decoupled from the EntityMapper. However, what concrete ChildSchoolRelation (and thereby School) belongs to a certain child, we need the EntityMapper. So we would either need to pass the Mapper to each call that traverses our schema (`child.getSchool(this.entityMapper)`) _and_ consider this when caching (WeakMap or something), _or_ we have the EntityMapper at a reference to itself to each Entity it loads.
3. **Loading Entities multiple times:** Currently, the EntityMapper always constructs a new Entity object when loading (the same) ID from the Database. This will cause a large overhead when we have this lazy loading.

**Comment by liwde** [comment]
I'm also posting this in the new issue. It fits better there.

**Comment by TheSlimvReal** [comment]
As long as we don't find a more suitable solution, we should try to use PouchDBs map/reduce functionallity. 

Therefore I would set up two indexes to allow calls ChildID -> ChildSchoolRelation and SchoolID -> ChildSchoolRelation. 

Maybe we could also add a third one where we also order them by date to more easily get the latest (current) one.

After setting up this Indixes we can (more) efficientliy search for the relations of a child/school.

It is not a very generic aproach but I think we should implement the ChildSchoolRelations as soon as possible so other parts of the application can start using this functionallity.

**Comment by sleidig** [comment]
PR #239 the main points of this ticket. A refactoring to simplify the implementation (#249) is due after EntitySchema has been merged.

Related to the feature of the "schools of the child" feature is also #207
