### ISSUE TITLE
Undo in admin entity details does not reset datatype

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#2165]
**To Reproduce**
1. Go to Child
2. Click on Edit Data Structure
3. Edit label of a field
4. Save
5. Click undo
6. Label is still the edited one

**Expected behavior**
Label should reset to initial value.

**Additional context**
Undo works on moving fields, so it seems that only the entity schema is not correctly reverted.

**Comment by sleidig** [comment]
Interestingly, this only happens on "name" and not on motherTongue or other custom fields:
If undo re-establishes previous config that did not define custom field details for a field that is also defined in code in the class, then that attribute is not reset currently.

**Comment by sleidig** [comment]
Currently we do not store the original schemas initialized from the code entity classes separately from the schemas that are dynamically overwritten by config. So no way to get back to the original field schema from code after it was overwritten (until an app reload).

Thinking more broadly about undo functionalities and UX:
- Should the user be able to reset a "base field" to its original state (as defined in code - or possibly in a base config template like codo's) through the UI?
- Should the user be able to reset a whole entity to its original state (i.e. all the fields and other settings)?

I think this may become useful (or even critically important) in a more advanced setup and admin UI, so discussing ways to store/reset original schemas should also have this in mind a bit.
