### ISSUE TITLE
Change detection does not correctly work in async dynamic components

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#2167]
**Describe the bug**
Sine #2101 in some dynamic components a manual change detection trigger is required in order to correctly display the updated state. It seems to be the case for components that initialize data asynchronous.

**To Reproduce**
1. Go to Notes Manager
2. See linked authors and children are displayed as "1 in total"

**Expected behavior**
It should show the `DisplayEntityComponent` if there are less than five linked entities

**Additional**
Adding a `changeDetectorRef.markForCheck` e.g. in `DisplayEntityArray` after the entities have been loaded the component works as expected. This was not required before.

**Comment by sleidig** [comment]
I think the `ChangeDetectionStrategy.OnPush,` for EntityFieldViewComponent is the culprit. Removing that fixes Notes Manager for me
