### ISSUE TITLE
No Error Handling / check for missing attributes in Notes

### ISSUE THREAD

**Issue by liwde** [Aam-Digital/ndb-core#218]
When opening the Notes with `"useTemporaryDatabase": false` in the `config.default.json`, a pretty non-descriptive error-message is shown in a red Message-Toast: "missing(undefined)"

In the console, a few more messages appear: The DB could not find an entry to be loaded (`{"status":404,"name":"not_found","message":"missing","reason":"missing"}`) and a later error where `hasPhoto()` is called on `undefined`. It seems like the Child related to a Note is not found resulting in the error.

In fact, `Note:1536258354699` references a child `Child:new` that does not exist. So to fix this now, we could just delete the Note. However, we need to also think about fixing the root cause:

# 1. No Error Handling

`child-block.component.ts` has no error handling:
```ts
ngOnInit() {
    if (this.entityId !== undefined) {
      this.entityMapper.load(Child, this.entityId).then(child => {
        this.entity = child;
      });
    }
  }
```

I'm not sure if we could let an error here bubble up to the containing `notes-manager.component.html` to somehow remove the child from the Note, or whether a simple in-place message "Child deleted" would be better.

However, this relates to...

# 2. Foreign Key Handling

I don't know what happened to `Child:new`, but it must have been deleted somehow. Today, this is possible from our UI, which directly uses the EntityMapperService to delete the Entity. However, this does not delete foreign keys (e.g. in Notes) or even Entities (e.g. the ChildSchoolRelationship). Are there already ideas on how to handle this? Otherwise, we should think about a concept on how to handle cases like this.

**Comment by sleidig** [comment]
Somewhat related: The current live system was broken due to a record with `note.date = null`, causing the NotesManager to remain blank without showing any notes. Console logged the error

> Uncaught (in promise): TypeError: Cannot read property 'getTime' of null

We do need better error checking. Maybe this should best go into the Entity sub-classes like `Note` itself (should we define getters?) and fill it with a reasonable default value or some kind of "Null Object". Then we don't have to repeat ourselves with error checking conditions all over the place.

**Comment by sleidig** [comment]
I would suggest to limit this issue to the error handling / attribute checking.

@liwde, do you want to create a separate issue for the Foreign Key Handling / cascading delete / ... question? That sounds like a big but important topic.

**Comment by liwde** [comment]
@sleidig, I completely agree, these are two different issues. I opened #220 for the long-term solution, so we can focus on handling the immediate effect and error-handling for Notes here.

**Comment by Lorsbyjm** [comment]
So the solution for this issues is to define getters for every attribute to check if a value is set or return a null object. Then we set the attributes to private and have to change all access to each of them. Am I right @liwde @sleidig ?

**Comment by liwde** [comment]
This is not about getters and setters, but the object itself being undefined. Instead, we must create a `.catch(error=>...)` to display a reasonable error and handle the child being undefined at the UI.

**Comment by Lorsbyjm** [comment]
Okay, so this ist still facing two problems. The first one, lukas mentions, about missing error handling and deletion of Objects. 
And the second one,  getters ans setters for objects. 
I think the firts one in now more important.

**Comment by sleidig** [comment]
As far as I understand it, PR #225 fixes the discussed points. @liwde, @Lorsbyjm please reopen this or create a new ticket if I am missing something.
