### ISSUE TITLE
Implement an "add photo"-functionality

### ISSUE THREAD

**Issue by RichardNutt** [Aam-Digital/ndb-core#223]
Currently there is no way of adding new photos through the app...
There might be a problem with the error-handling when displaying images, see Issue #213.

**Comment by sleidig** [comment]
Allowing users to add photos is definitely needed.

Connected to the larger issue of how we can deal with any kinds of files: #89

**Comment by liwde** [comment]
Nextcloud config: https://github.com/nextcloud/server/issues/3131#issuecomment-489179454

**Comment by sleidig** [comment]
done through Nextcloud integration with PR #306 
Big thank you to @RichardNutt !
