### ISSUE TITLE
account-backend can't find user anymore

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2247]
see https://aam-digital.sentry.io/issues/4471309463

Errors are thrown in accounts-backend because a user is not found when the frontend requests the user entity including new prefix. Probably we shouldn't request by entity but by keycloak user?!

**Comment by tomwwinter** [comment]
Issue reason found in account-backend. Expected behaviour, can be ignored. As part of the research process, sentry was enabled on account-backend on dev and prod.
