### ISSUE TITLE
Support Internationalization (multiple languages/translations)

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#226]
To become a flexible system for different organisations, we should implement Internationalization, i.e. translation of the UI into different languages and locales.

Angular supports this: https://angular.io/guide/i18n

**Comment by sleidig** [comment]
General questions and considerations:
- needs to work with service-workers offline
- How do we extract the placeholders?
- What about default labels that are stored in config rather than code?
- How can the translations be maintained? Are there easy tools that we can give an organisation to create translations?
- if translations are built into the app - how do we manage different language app deployments on the server?

**Comment by Schottkyc137** [comment]
- Offline should not be a problem. Changing the language offline could be, but I don't think there's anyone really interested in that
- The placeholders (Assuming you mean the i18n placeholders) are extracted and updated automatically using a script (see package.json -> extract-i18n)
- This is a point I don't have an answer for and that we need to think about in detail
- The tools will extract the texts, placeholders, and remarks and put them all together in a standardized file. There are tools that allow easy access and editing capabilities to this file. However, I have yet to find a tool that supports the {{}} string-interpolation mechanism in a way that doesn't look too complex.
- That is also something to further think about. Angular suggests [this](https://angular.io/guide/i18n#deploy-multiple-locales)
- That is true
