### ISSUE TITLE
Manage database changes due to app upgrades

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#230]
From time to time a new version of the app may require changes in the database (e.g. #210 requires an added new field to all entities in order to make them searchable). We should implement a dedicated Module to manage such upgrades.

The UpgradeModule should:
- [ ] add database entry to indicate the current database version
- [ ] warn users if their app version does not match their database version (and refer them to their system administrator?)
- [ ] add a UI for admin users to trigger database upgrades (and/or make this a shell script to be executed during deployment on the server?)

**Comment by TheSlimvReal** [comment]
We could trigger the database update on the build of the helgo branch or when a merge on the master happens. This is very easy to accomplish with travis deploy.

**Comment by sleidig** [comment]
The database change can't happen before the code base has been deployed. But once we actually use Continuous Deployment to upload the code that's an interesting addition to trigger it automatically.
Otherwise it could maybe be triggered automatically the first time any user logs in after a code update.

**Comment by sleidig** [comment]
This has not been an issue anymore over the last year. Partly this can also be achieved using our EntitySchema system: When you change the annotation of an Entity's field the next time it is loaded an adequate transformation can be triggered by that data-type annotation.
