### ISSUE TITLE
improve LoggingService and Sentry integration

### ISSUE THREAD

**Issue by tomwwinter** [Aam-Digital/ndb-core#2346]
Some errors are currently forwarded to Sentry with misleading or missing information about the actual Exception.

Needs investigation and research for the Sentry JS integration and adaptions ins our LoggingService to pass the needed informations correctly to Sentry.

**Comment by sleidig** [comment]
various improvements done in recent releases.

Closing this and will open individual issues for each of the remaining logging issues.
