### ISSUE TITLE
unit test SqlReportService occasionally failing

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2349]
for example see https://github.com/Aam-Digital/ndb-core/actions/runs/8737747356/job/23975672005?pr=2335

> 9 (Linux x86_64) SqlReportService should generate a valid schema including all properties FAILED
> #17 154.4 	Expected $.tables.SchemaTest not to have properties
> #17 154.4 	    test: 'TEXT'
> #17 154.4 	    at <Jasmine>
> #17 154.4 	    at UserContext.apply (src/app/features/reporting/sql-report/sql-report.service.spec.ts:79:24)
> #17 154.4 	    at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:368:26)
> #17 154.4 	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:273:39)
> #17 154.4 	    at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:367:52)

Re-running the test usually then passes it.

**Comment by sleidig** [comment]
@tomwwinter can you please briefly comment whether this service (and test) is still relevant at all?

**Comment by tomwwinter** [comment]
This service is kind of deprecated, so i would recommend to deactivate the failing test for now.
