### ISSUE TITLE
End-To-End (e2e) Tests

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#24]
In addition to unit tests ( #22 ) automated end-to-end tests for components need to be set up.

**Comment by sleidig** [comment]
Interesting additions for testing can also be [Storybook](https://storybook.js.org/docs/guides/guide-angular/) and [Percy](https://percy.io/) (automated UI testing)

**Comment by TheSlimvReal** [comment]
Lets first finish #1043 and then close this
