### ISSUE TITLE
support for sql reports without date range

### ISSUE THREAD

**Issue by tomwwinter** [Aam-Digital/ndb-core#2463]
_As a end use I want to create a report with optional or even without any date rage filter._

**Objective**
- [ ] Prepare UI for optional date range filter
- [ ] support in backend for non-date range filter

**Proposed Solutions & Alternatives**
- [ ] make date range filter optional in frontend or hide if no date range is configured in selected report 

--> fix frontend bug
--> finalize backend support for ranges: https://github.com/Aam-Digital/aam-services/pull/17

**Comment by sleidig** [comment]
it seems the reporting is currently broken for any report, even the legacy frontend-run system:
![image](https://github.com/user-attachments/assets/a04348f7-b929-4fb5-9ac2-1a0d3653474d)
