### ISSUE TITLE
Can't scroll to bottom

### ISSUE THREAD

**Issue by jana47** [Aam-Digital/ndb-core#252]
For example on the dashboard or the attendance register I can't scroll to the bottom. Only on full screen.

**Comment by sleidig** [comment]
Confirmed. Actually, this is an issue for me no matter if in fullscreen or not.

I think this has something to do with the HTML elements' size and positioning. We had similar problems before - unfortunately I can't find anything about it anymore.

**Comment by sleidig** [comment]
Original bug (seems to be a problem in Firefox, Chromium displays fine):
![image](https://user-images.githubusercontent.com/1682541/68740582-af04c400-05eb-11ea-8aec-5914a67f55a4.png)

**Comment by sleidig** [comment]
After PR:
![image](https://user-images.githubusercontent.com/1682541/68740774-276b8500-05ec-11ea-8dc9-c0d55a86b148.png)
