### ISSUE TITLE
unit tests are failing from time to time

### ISSUE THREAD

**Issue by tomwwinter** [Aam-Digital/ndb-core#2545]
**Describe the bug**
Currently, our tests are failing from time to time. We need to check, if all tests are resetting the test environment correctly.

**To Reproduce**
No easy way, just re-run all tests

**List of observed failing tests**

- EditTextWithAutocompleteComponent should show all entities of the given typ
- AdminEntityFormComponent should move all fields from removed group to availableFields toolbar

**Comment by sleidig** [comment]
Looks like this has been fixed with some corrections made over the last week. Have not seen test failures anymore
