### ISSUE TITLE
Improve overall performance of loading data

### ISSUE THREAD

**Issue by codingfabi** [Aam-Digital/ndb-core#257]
For a overview, what's the performance on the live system currently like? @sleidig can you give us a quick update about that and the satisfaction level of the users?

Furthermore, could we list things that can be done to boost the performance like implimenting search indizes etc.?

-----
**Summary of (possible) performance issues:**
- Building database indices (pouchdb needs much longer for the first query after changing an index compared to later queries)
- loading data from database (especially if we need multiple queries of different entity types to combine more complex objects): #462
- creating/updating Angular components (our long lists are loading very slow, especially if they include a lot of subcomponents. this probably has to do with angular change detection)

-----
**Relevant tools and approaches:**
- do change detection profiling (e.g. with https://chrome.google.com/webstore/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh)
- switch some components to the "OnPush" change detection strategy
- ...

![image](https://user-images.githubusercontent.com/1682541/126469505-4800b9d4-0bd6-4632-a04c-e6599b870735.png)

**Comment by sleidig** [comment]
There haven't been any complaints about performance. Overall it is usable but some areas are noticeably slow. 

Some roughly stopped response times:
* "Children" (populating the list of all current children): 4-5 seconds
* "Notes" (loading the list of all notes): 3-4 seconds

The bottleneck is _not_ the server, as all this data is loaded from the PouchDB local database. But our naive implementation of the database requests may be an issue and the large number of related data (together with the children we load each child's school and recent attendance records). Also, I have heard that PouchDB is quite slow generally with larger loads.

One larger thing we could consider is implementing a caching system, that keeps for example the array of Child objects in memory rather than always loading them from disk through PouchDB. (or maybe there is even a PouchDB plugin for this?)

**Comment by Lorsbyjm** [comment]
@TheSlimvReal  and @Sepper007  wrote a script to create demo data for the demo database (~500 children with 1500 records).  In the following we will dicuss the resolving performance/loading issues:

**Problem description (children-list):**
Right now we fetch all children with one database call and then load the school and attendance information with one call each. This results in over thousand database calls (500 children * (1+1 school + 1 attendance information).
School call: returns the id of the current school and then load this school in a second call


**Solution 1: Filter in Frontend**
Remove the two extra calls for the school. Therefore load all ChildSchoolRelations and Schools with the Childs. The mapping is then done in the frontend. 
Todo:  Therefor the SchoolBlockComponent must be rewritten to get the School object and not just an id.

**Solution 2: Asynchron data loading**
Do everything as it is, but show data when it is there.
!!! Dirty Cecks in view possible !!!

**Comment by sleidig** [comment]
`SchoolBlockComponent` does support to take either an id or an object as input. If you want to avoid the block loading the entity itself, simply don't pass an id but `<app-school-block [entity]="mySchoolEntityObject">`.

Do you wanna post your demo data script here to potentially reuse it when it's needed again?

**Comment by codingfabi** [comment]
@TheSlimvReal @Sepper007 what is da status quo on this one? do you have any solutions or improvements planned?

**Comment by liwde** [comment]
I'm experimenting with this in https://github.com/Aam-Digital/ndb-core/compare/entity-cache.

A thing I observed was that the EntityMapper always created new objects on read. That seemed excessive to me. My first experiment adds a simple cache at the entites, and while reading Children (~600 in the DB), there are ~500 cache hits. Similar things are observed when reading notes (~7000 in DB, ~6000 cache hits counted).

Currently, I added a basic LRU cache without any fine tuning. The best option, a Map of WeakRefs is not available yet and needs browser support anyways, but it could be added at any point to further improve performance.
I'll add some Unit Tests, but this is a fairly easy addition.

Another improvement could be made with real pagination (not loading all 7000 notes, but just 100 at a time), but we'll need to find a more generic concept for that.

**Comment by sleidig** [comment]
maybe the new pouchdb indexeddb adapter could also boost performance once it gets published: https://github.com/pouchdb/pouchdb/issues/7861

**Comment by sleidig** [comment]
This article series is very interesting and helpful: https://blog.ninja-squad.com/2018/09/20/angular-performances-part-3/
We should look into profiling/measuring the performance and improve the change detection efforts (it seems like the UI and components are more of a bottleneck for us than the database loads).

In general, we should maybe also integrate Lighthouse into our PR CI: https://github.com/marketplace/actions/lighthouse-ci-action

**Comment by sleidig** [comment]
very useful explanations: https://devchat.tv/adv-in-angular/aia-290-angular-performance-with-christian-liebel/

**Comment by sleidig** [comment]
also relevant: do change detection profiling (e.g. with https://chrome.google.com/webstore/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh)

**Comment by TheSlimvReal** [comment]
The performance has been analysed and multiple improvements implemented. Some last profiling and improvements have been done in #1891.

Closing this now. Once there are new performance problems, a new issue can be opened.
