### ISSUE TITLE
Make Entity-Subrecord editable in small screen

### ISSUE THREAD

**Issue by Lorsbyjm** [Aam-Digital/ndb-core#259]
In the first version of responisve design the edit functions are disabled on a small screen because often the edit is done inline but the line gets bigger than the screen.

Is it possible to design the UI in a way to allow editing on small screens? Or should mobile users always edit in a popup dialog? (But the dialog is only available if it is explicitly set up in code. Maybe we need an auto-generated default popup form component then.)

![image](https://user-images.githubusercontent.com/9371498/57478755-0f612480-729c-11e9-84e3-9a4f4abe59ce.png)
![image](https://user-images.githubusercontent.com/9371498/57479090-f1e08a80-729c-11e9-8ff4-071d1c5a110a.png)

**Comment by sleidig** [comment]
from a UX perspective I think it is preferable to show users a popup on small screens. This is already possible but needs to be considered when implementing new sections (i.e. setting a detail component to enable the popup).
