### ISSUE TITLE
Attendance status sometimes not saved

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2615]
**To Reproduce**

1. Create a new note and select category "school class" (or another type allowing attendance participants)
2. Add new children and select an attendance for each in the drop-down 
3. Save and reopen that note 
4. Often/sometimes the drop-down for attendance status of the children is empty again

**Comment by tomwwinter** [comment]
When opening Add Note Dialog, this error is logged to console: 

![Image](https://github.com/user-attachments/assets/a37218cc-428c-47e5-b9a4-b55a3d339301)
