### ISSUE TITLE
Custom Logo / Image on Public Form

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2626]
_As an adminstrator I want to quickly add a custom logo to our public form in order to make this more polished for external users._
Public forms allow to give access to outside "users" without a login to submit data, e.g. in a self-signup form for participants. These forms can already contain a simple introductory text and title but should allow admin users to easily customize the design a bit further by adding a visual image to the form as well

**Objective**
Extend the `PublicFormConfig` class to also hold an image property and extend the component to display that image. Configuration and storage can be implemented in a similar way to the SiteSettings code, where admins can define a app-wide logo displayed in the navigation menu.

**Comment by Abhinegi2** [comment]
@sleidig , just wanted your input on how would you prefer the custom logo/image to be placed
1.  in the top-right corner of the form, 
2. should it be positioned in front or above the public form title?
![Image](https://github.com/user-attachments/assets/613cee23-9265-4b55-84f4-9c4429e5d321)

**Comment by Abhinegi2** [comment]
> [@sleidig](https://github.com/sleidig) , just wanted your input on how would you prefer the custom logo/image to be placed
> 
> 1. in the top-right corner of the form,
> 2. should it be positioned in front or above the public form title?
>    ![Image](https://github.com/user-attachments/assets/613cee23-9265-4b55-84f4-9c4429e5d321)

or it should look like this -
![Image](https://github.com/user-attachments/assets/56649197-94d7-49c1-a251-97d3dc78007c)

**Comment by sleidig** [comment]
Good question ... I'll ask our users for input on this for the final version. Thanks for the screenshots, that'll be useful for the discussion.

My initial thought was to put it below title, above description as a full "row" (in case someone has a very wide logo/image that would fill the width). Maybe let's start with that initially
