### ISSUE TITLE
Manage translations outside of repository using a specialized software

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2642]
Currently, UI translation keys are extracted using an npm script, manually translated and then commited in our git repository. This requires the translator to have git access and be comfortable with a large, technical xml (.xliff) file. Instead, we should use some cloud-based system to manage translations to outsource these tasks and decouple them from software development.

https://poeditor.com/ is free for open source projects and could be a good solution

EDIT: our project has been approved for the free FOSS licence
**_https://poeditor.com/projects/view?id=740876_**

-----
An ideal process would be:

Automatic updates of tokens for translation:
- whenever there is an update to "master" branch, the translation platform automatically receives updated translation tokens
- (status quo: we need to manually run `npm run extract-i18n` and then commit the updated files to git

Automatic updates of translations for app users:
- ~whenever someone adds/updates a translation for a token in some language on the translation platform, the translations for deployed systems automatically update for users~
  - ~this would make corrections to translations faster and easier~
  - ~how can different app versions be handled with this? (some systems might run an older version, where certain translation tokens are different - so the system would need to have version-related translations?)~
  - ~if translations are loaded by devices directly, we need to ensure they are cached by service worker so that offline-functionality is fully supported~
  - ~this approach will require code changes to dynamically load translation files instead of delivering them as static angular assets (which is the current approach)~
- **OR**: we can easily open a PR in GitHub to commit new translations that were done on the translation platform
  - this would allow us to keep the existing architecture where translation files are part of the code base and packaged with the app directly

--> read about approaches recommended by POEditor; they support CI integration with GitHub etc.

**Comment by sleidig** [comment]
For now, it seems best to _not_ change the architecture how translation files are delivered to users (i.e. stick with the translations being part of our code repository; option 2 above) and get the integration with the translation platform set up. We can always come back to the question of delivering translation files to users dynamically (independent of a new app release) at a later time.

**Comment by tomwwinter** [comment]
> I’ve documented the current behaviour and the proposed solution in this [Document](https://docs.google.com/document/d/1Th2UYISml-Q8flXO4yrwX49kgkN8LvkdH0mMWm-N66E/edit?tab=t.0) for better clarity and understanding.

Can you please mask all api_tokens in this document?

**Comment by Ayush8923** [comment]
> @Ayush8923 did you explicitly do anything during import to POEditor to mark all as translated? In French, for example, [the .xls file](https://github.com/Aam-Digital/ndb-core/blob/master/src/assets/locale/messages.fr.xlf) has some entries with `state="new"` (i.e. untranslated). But POEditor lists those as translated, showing the English text as the translation ... Can we get those shown as "untranslated" there somehow?

No, @sleidig, I did not enable any such setting during the terms and translation import, and there was no option like "translate all sources" while importing. During the import, we only had the options shown (for reference, I have added the screenshot below). There is an option here to choose whether we want to translate from the source tag or the target tag.
<img width="587" alt="image" src="https://github.com/user-attachments/assets/cea7fde9-8285-4795-8860-b9fa1cce108d">

**Comment by Ayush8923** [comment]
> ase mask all api_tokens in this d

@tomwwinter I have added the `POEDITOR_API_TOKEN` and `POEDITOR_PROJECT_ID` in this [document](https://docs.google.com/document/d/1Th2UYISml-Q8flXO4yrwX49kgkN8LvkdH0mMWm-N66E/edit?tab=t.0).

**Comment by tomwwinter** [comment]
> > ase mask all api_tokens in this d
> 
> @tomwwinter I have added the `POEDITOR_API_TOKEN` and `POEDITOR_PROJECT_ID` in this [document](https://docs.google.com/document/d/1Th2UYISml-Q8flXO4yrwX49kgkN8LvkdH0mMWm-N66E/edit?tab=t.0).

Sorry, i ment that there are credentials (api_tokens for poeditor) are visible in the screenshots. Please make sure to never share or screenshot credentials.

**Comment by tomwwinter** [comment]
> @Ayush8923 did you explicitly do anything during import to POEditor to mark all as translated? In French, for example, [the .xls file](https://github.com/Aam-Digital/ndb-core/blob/master/src/assets/locale/messages.fr.xlf) has some entries with `state="new"` (i.e. untranslated). But POEditor lists those as translated, showing the English text as the translation ... Can we get those shown as "untranslated" there somehow?

Regarding the specification, "new" just means, that there is a property which was not there in the previous version. The correct value would be "needs-translation"

see: http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#state

**Comment by sleidig** [comment]
I think maybe the best practice here would now be to use only `ng extract-i18n` and send the generate xlf files without any target translations to POEditor? --> https://angular.dev/guide/i18n/translation-files
We can maybe then remove the `xliffmerge` dependency because POEditor is merging the existing translations with the new xlf for us?

@Ayush8923, did you find any documenation or recommendations about this with regards to setting up angular translations in POEditor? (or could you otherwise try to find this out for us?)

**Comment by Ayush8923** [comment]
@sleidig, thank you for your suggestion.

Yes, in the GitHub action, we set up for POEditor integration, we are indeed using the `ng extract-i18n` command to generate the translation files and send them to POEditor. However, the language files generated by this command currently include the target tags.

From my research, I found this relevant pieces of documentation regarding POEditor and Angular:
1. [Angular 2 Localization: How to Translate App Strings](https://poeditor.com/blog/angular-2-localization-how-to-translate-app-strings/)
    This documentation outlines a process where POEditor can be integrated directly with GitHub. However, as we last checked, this requires a POEditor membership plan to enable the GitHub integration feature.
    
If needed, I can look further into whether removing the `xliffmerge` dependency and directly managing translations via POEditor aligns with best practices. Let me know your thoughts!

**Comment by sleidig** [comment]
1. Is my understanding correct, that POEditor should/can receive xlf files "without" target tags? Will POEditor merge previous existing translations with such a new upload, so that we don't lose the previous work?
2. If so, does ng extract-i18n or another public tool support generating xlf without target (or removing those tags)?

**Comment by Ayush8923** [comment]
1. Yes, POEditor can receive XLIFF (.xlf) files without the target (<target>) tags. POEditor is to handle and merge translations, so when we upload a new XLIFF file without the <target> tags, it will typically merge the new file with any existing translations, preserving the previous work where applicable. 

2. The `ng extract-i18n` tool, used in Angular for extracting translation files, typically generates XLIFF files with the `<target>` tags populated based on existing translations. If we want to generate an XLIFF file without the `<target>` tags, I think, we might need to manually remove them after extraction or use a custom script for this purpose. I think, There isn't a built-in flag in ng extract-i18n specifically to omit the <target> tags, so we would need to either manipulate the generated file.

**Comment by Ayush8923** [comment]
> 1. Is my understanding correct, that POEditor should/can receive xlf files "without" target tags? Will POEditor merge previous existing translations with such a new upload, so that we don't lose the previous work?
> 2. If so, does ng extract-i18n or another public tool support generating xlf without target (or removing those tags)?

1. Yes, POEditor can receive XLIFF (.xlf) files without the target (<target>) tags. POEditor is to handle and merge translations, so when we upload a new XLIFF file without the <target> tags, it will typically merge the new file with any existing translations, preserving the previous work where applicable. 

2. The `ng extract-i18n` tool, used in Angular for extracting translation files, typically generates XLIFF files with the `<target>` tags populated based on existing translations. If we want to generate an XLIFF file without the `<target>` tags, I think, we might need to manually remove them after extraction or use a custom script for this purpose. I think, There isn't a built-in flag in ng extract-i18n specifically to omit the <target> tags, so we would need to either manipulate the generated file.

**Comment by sleidig** [comment]
Okay. I think the objective and required outcome is clear:

- POEditor must tag untranslated parts, so that a translator can use the filter for "untranslated" on the platform there

It may be useful or important to have the original English as default <target> terms (would the app otherwise display completely empty text also?) or not - that might need research or testing.


----
@Ayush8923 : Can you manage to research and implement a final solution for this problem with the help of your team?
