### ISSUE TITLE
public-form view throws exception if the form-config does not exist locally

### ISSUE THREAD

**Issue by tomwwinter** [Aam-Digital/ndb-core#2657]
**Describe the bug**
When a user open a public form with an id that does not exist in the local database, an unhandled exception is thrown.

**To Reproduce**
Start application locally

1. Go to some non existing public-form: http://localhost:4200/public-form/123f
2. See error

**Expected behavior**
We should handle all errors and show a 404 error page.

**Screenshots**
![image](https://github.com/user-attachments/assets/b2d4b5cf-fc5c-4343-88ab-4069b364110e)

**Desktop (please complete the following information):**

- OS: all
- Browser: all 
- Version: 3.42.2

**Additional context**

**Comment by sleidig** [comment]
Is this still happening after the latest changes, @Abhinegi2 ?

**Comment by Abhinegi2** [comment]
Yes, @sleidig It is still happening let me look into this issue

**Comment by Abhinegi2** [comment]
@sleidig
While reviewing the current approach for handling public forms, I found two possible ways to address errors:

1. **Redirect to a 404 Page**
Use a try-catch block to detect errors and redirect to the existing 404 page. However, if we choose this option, we may need to modify the HTML of the 404 page, as it currently includes a "Go to Dashboard" button, which might not be relevant in this context.
2. **Handle Errors Within the Component**
 If the public form configuration does not match any valid entry, we can set an error state within the component itself and display an error message (e.g., "Form not found") directly in the template, instead of redirecting to a 404 page. 

Let me know your thoughts on these approaches

**Comment by sleidig** [comment]
Thanks for working this out!

In this specific context (the component is used by external visitors also, in contrast to all other parts of the app) I think it'll be more clear and flexible to go with (2), i.e. adding error handling to the component itself

**Comment by george-neha** [comment]
Changes are working according to the functionality. Can be pushed for review.

**Comment by Abhinegi2** [comment]
@george-neha, could you please test the following cases on the [dev site](https://dev.aam-digital.net/)?

1. Non-existent Public Form
- Try to access a public form that does not exist.
- Verify that the message displayed is:
"The form you are looking for is either unavailable or doesn't exist. Please check the link and try again."
Access without Required Permissions

2. Access a public form that exists but requires permissions you do not have( Currently, only child-related public forms are accessible.)
- Try to access a public form with an entity type other than "Child.
- Verify that the message displayed is:
"You do not have the required permissions to submit this form. Please log in or contact your system administrator."

**Comment by george-neha** [comment]
Tested this. error message are being displayed for Publics forms if:
1. a public form that does not exist
2. if the required permissions are not there

**Comment by sleidig** [comment]
Any suggestions on polishing the UI a bit (visual, layout or wording, etc.), @george-neha & @Abhinegi2 ?
![image](https://github.com/user-attachments/assets/250d4884-2467-4ab6-b13c-2ac30ec416a2)

It definitely fulfills the purpose already but it feels rather raw to me. That little something, extraordinary attention to detail to make it pretty, is still missing, in my opinion.
(e.g. the way only the very top of the page contains the text and most screen is empty. Or the way the text has that lonely last word on the new line :sweat_smile: )

**Comment by Abhinegi2** [comment]
> It definitely fulfills the purpose already but it feels rather raw to me. That little something, extraordinary attention to detail to make it pretty, is still missing, in my opinion.
> (e.g. the way only the very top of the page contains the text and most screen is empty. Or the way the text has that lonely last word on the new line 😅 )


@sleidig and @george-neha  we can center-align the content, add some icons/buttons (e.g., "Support Email" or "Go to Login"), and maybe then it looks good 
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/5313642b-c342-43e9-94fa-224465e1453b" />

**Comment by sleidig** [comment]
Links to login or "home page" do not make sense in this specific context in my opinion: The visitors of a public form do not have an account or access to any other section except the exact form they have been shared through the link.

I think centering this on the page already helps a lot in making this look a bit more polished. Happy to go ahead with just that change. Maybe try the icon above the title in your draft, to have an even stronger centered symmetry?

**Comment by Abhinegi2** [comment]
Sure let me make these changes.

**Comment by Abhinegi2** [comment]
please let me know which one looks good-
1. 
<img width="1506" alt="image" src="https://github.com/user-attachments/assets/a2ba8af4-01fa-42d0-992c-aeb7fe6d7e95" />
2. 
<img width="1494" alt="image" src="https://github.com/user-attachments/assets/ddaa9778-845a-4c89-bbd0-faa7f3948132" />

**Comment by sleidig** [comment]
Cool. I also vote for (2).
Give it a bit more margin between icon and text, however.

**Comment by Abhinegi2** [comment]
@george-neha can you please test it again?

**Comment by george-neha** [comment]
Working as per the functionality and the discussions we had.
