### ISSUE TITLE
See unread notifications indicator in the app

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2660]
_As a user I want to see at a glance if there are new notifications for me while I am working within the app._

Independent of system push notifications, within the app itself users should have access to their notifications through an icon in the top toolbar, following the common design pattern of other platforms. 

- [x] If there are unread notifications corresponding to the user we can show the count of the unread messages in the bell icon. 
![image](https://github.com/user-attachments/assets/fff81275-4418-4df0-8d9b-aa935190bc8c)
- [x] Implement the logic to get the total number of unread messages and display the count in the notification bell icon.
- [x] Added the check if there are not any unread messages then we don’t need to show the count of unread messages.

- Clicking on the icon should #2661

**Comment by Ayush8923** [comment]
@sleidig I have made some updates in the issue description.

**Comment by sleidig** [comment]
This looks good :+1: 

As this issue is about the UI aspect, you can implement it with a service delivering mock data. But I have also added a new issue to discuss the storage of actual notification event records now here: #2690
