### ISSUE TITLE
View list of notifications in the app

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2661]
_As a user I want to see details of all my notifications in the user interface of the app in order to not rely on the system push messages that can be discarded quickly._

Within the app itself users should be able to view a list of notifications with some details about each notification (e.g. title, description, at a later stage also an action button).

- should be accessible from the #2660 
- This task includes:
  - [x] To show the list of notifications, we can show the same notification bell icon, when the user click on that icon the list of the notification list will be shown. For reference, Added the screenshot of the notification list (this list shown after clicking the notification bell icons).
![image](https://github.com/user-attachments/assets/cc7ef569-0391-488f-9171-de78b7dc590e)
- [x] Whenever the user clicks on the bell icon then the list of all the notifications will be displayed corresponding to the user, so user can read the notification from the list.

- Next tasks building on this:
  - #2690

**Comment by Ayush8923** [comment]
@sleidig So far, I have implemented the notification UI by referring to the screenshot mentioned in the issue. For reference, I have added the screenshot below. I still need to do code cleanups, which I am gradually doing during development.

<img width="808" alt="image" src="https://github.com/user-attachments/assets/2f3ba15d-eaf2-419d-a440-2557eaef46d6">

1. When the user clicks the settings button, a toggle option will appear, allowing them to turn their notifications ON or OFF. For reference, I have added the screenshot below.

<img width="372" alt="image" src="https://github.com/user-attachments/assets/38ded848-7aa3-4dc5-a663-48cd89b44296">

If the notification list is very long, how many notifications should we display initially before allowing the user to scroll through the rest? Please feel free share your thoughts/suggestions on this.

**Comment by Ayush8923** [comment]
@sleidig I am conducting research to improve the notification list UI. We can add the two tabs inside the notification list: 
1. All: The **All** tab displays all notifications.
2. Unread: The **Unread** tab displays only unread notifications.

Additionally, when the user clicks on the three dots (menu icon), multiple options should appear, such as:
- Notification Settings
- Enable Notifications

From this menu, users should also be able to navigate directly to the **Notification Settings** page inside the profile. This enhancement aims to improve user experience and provide quick access to relevant notification management options. Please let me know your suggestions and thoughts on this.

<img width="353" alt="image" src="https://github.com/user-attachments/assets/2b538cea-2487-4e03-ac5c-5bc6e08f711e">

**Comment by sleidig** [comment]
Thanks. This looks like good additions. 

I would also like to see an unread indicator (often a small dot) for each notification event and the option to mark an event as read/unread (maybe by clicking on that indicator)

**Comment by Ayush8923** [comment]
@sleidig For unread notifications/indicators, we can display a blue dot for each unread notification. Also, a three-dot menu will appear when the user hovers over a notification. This menu will allow the user to mark the notification as read or delete it. 

For reference, here is the UI snapshot.
![image](https://github.com/user-attachments/assets/87b096c5-b5ed-43b1-b2e6-b3d8e5387385)

**Comment by sleidig** [comment]
Cool :+1:   Maybe we can show that context menu on hover of the indicator dot (and show and empty circle for read notifications) to reduce UI complexity with one less layout element
