### ISSUE TITLE
CouchDB Fauxton doesn't work correctly

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#267]
[Fauxton](http://couchdb.apache.org/fauxton-visual-guide/), the GUI database browser of CouchDB, accessible at https://demo.aam-digital.com/db/_utils/  doesn't work correctly in our setup and throws errors.

This may be due to the fact that CouchDB is reverse-proxied to a "subfolder" URL, see https://issues.apache.org/jira/browse/COUCHDB-3155

**Comment by sleidig** [comment]
see https://github.com/apache/couchdb-fauxton/issues/1199 
fix/workaround seems to be available

**Comment by RNCTX** [comment]
This seems rather fragile, and perhaps the source of issues I was having in another thread I thought were user/pass related.

I am trying three urls:  sub.do.main/couchdb/_utils, sub.do.main/couchdb/_utils/, and sub.do.main/couchdb/_utils/#login. I have Nginx set up to reverse proxy that directory per the docs.

1) Safari 13.1 on OSX 10.15.4 loads the web ui for me at sub.do.main/couchdb/_utils/, it gives me an "unauthorized" json response without the trailing slash at sub.do.main/couchdb/_utils and also the same "unauthorized" json response at sub.do.main/couchdb/_utils/#login
2) Chrome 81.0.4 gives me an "unauthorized" json response at all three urls.
3) Firefox 76.0.1 gives the same as Chrome, "unauthorized" json response at all three urls.

When Safari does load the web ui, it loads to the database tab of the web ui with an endless loading animation.  Clicking on another tab will redirect to the login box.  Chrome and Firefox never produce a login box at any of the three urls above, only "unauthorized."

My install reflects the reply above this one ("databaseBaseURL" is like that, with URL capitalized).

**Comment by sleidig** [comment]
Hi @RNCTX, thanks for your comments. I am not sure which server or setup you have been testing - our default docker image maps "/db" to the CouchDB server rather than "/couchdb".

Using the latest docker image (`image: couchdb:3`) finally fixes this with the pre-packaged Fauxton, however :-)

There is still an inconvenience of Angular grabbing the /db route and not letting you get through the fauxton if service-workers are installed. But as this issue is resolved with the latest CouchDB I am closing this issue.

@RNCTX  if you need help with anything related to this, still feel free to comment here with further details!

**Comment by RNCTX** [comment]
I figured it out, if anyone else stumbles into the same issue, `require_valid_user` restricts the web interface.  Safari was finding its way past the login page to the database page (but unable to finish loading the page due to lack of authentication), whereas Chrome and Firefox 401 or 403 at the login page.

You guys should probably exempt /_utils/#login from `require_valid_user` checks.
