### ISSUE TITLE
Penetration Testing

### ISSUE THREAD

**Issue by RichardNutt** [Aam-Digital/ndb-core#269]
With regard to pentesting the application we ran an arachni and openvas scan, as suggested in [Issue #144](https://github.com/NGO-DB/ndb-core/issues/144#issuecomment-489630549).

- arachni result (4 Issues):
[arachni.zip](https://github.com/NGO-DB/ndb-core/files/3195214/arachni.zip)
- (The openvas scan was inconclusive on my machine. I might have messed up the setup...
[openvas.zip](https://github.com/NGO-DB/ndb-core/files/3195216/openvas.zip))

**Comment by Lorsbyjm** [comment]
@RichardNutt @YoshiAndMath Did you do any analyzation of the results?
Can we derive any todos?

**Comment by RichardNutt** [comment]
The relevant problems reported by arachni were the following:

- [ ] The server responds to https://demo.aam-digital.com/db/; which is unreferenced in Angular. (Note: This directory exists to circumvent CORS problems.)
- [ ] Missing 'X-Frame-Options' header

I can't judge, if these are pressing issues or not.

**Comment by codingfabi** [comment]
AFAIK X-Frame-Options are a http feature to prevent clickjacking. 
Clickjacking is when a potential attacke overlays our applicatoin with dangerous software to "highjack" clicks or input. X-Frame-Options tells the browser if our application is allowed to be part of a <frame> (or something comparable) or not. 
Even though I think that this is not a potential attacking scenario we should discuss implementing this. 
The first probem indicates that CORS is not properly setup in our couchDB configuration. I think we should at least document how we used CORS in our couchDB setup. @sleidig can you tell us something about this?

**Comment by sleidig** [comment]
The route `https://<server>.com/db/` in our setup is configured to be reverse-proxied by the nginx webserver to pass requests through to the CouchDB running alongside the angular app. This is a common strategy (explained in detail for example here: https://lloydrochester.com/nginx/couchdb/proxy/2018/10/10/couchdb-nginx-proxy.html ) and has a couple of advantages:

* The database requests from the client are sent to the same server+port, therefore no explicit CORS needs to be configured
* TLS encryption of traffic can be done with the same certificates for the app and the database and no ssl options need to be configured for the CouchDB explicitly.

The security warning seems to relate to "forgotten" folders on the server that can be discovered. Our `/db/` route is explicit and maintained, so I think there is not that much risk on this.

PS.
Where could we document this information regarding CORS and reverse-proxy? What do our documentation masters suggest?

**Comment by Lorsbyjm** [comment]
@vlle1 You might be the one who nows the parts of the documentation best. Is there a setup or technic section where we should store all these information.

**Comment by vlle1** [comment]
I recommend just throwing it somewhere under compodoc_sources/guidelines. However, you should consider splitting the documentation in different parts: e.g. 'how to' and 'explanation' as mentioned at https://www.divio.com/blog/documentation/ 
or at least you should stick to one of those "documentation paradigms". It will make my work easier when I try to restructure the documentation so that it fits those criteria.

**Comment by sleidig** [comment]
I created an issue for the X-Frame-Options Headers: #312

Let's close this issue here once the information about reverse-proxy /db path is documented in our docs?

**Comment by sleidig** [comment]
https://www.zaproxy.org/ might be another interesting security testing tool

**Comment by sleidig** [comment]
Closing this, as the identified issues have their own issues created.
