### ISSUE TITLE
Store and access notifications & mark them "read"

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2690]
For the "notification centre" UI, it is necessary to store notification events in the same way as the user-facing functionalities:
- #2660
- #2661 

DISCUSS:
- Do we store events in CouchDB as "normal" entities, reusing our existing architecture? Or do we store these completely different?
- Is an event record specific for a single user or are these "global" events, that are viewed by all users who have activated that type of notification?

### We need to implement the below-mentioned functionality in the notification list.
- [x] Display all notifications in the `All` tab.
- [x] Show only unread notifications in the `Unread` tab.
- [x] When a user clicks on the three dots and selects "Mark as Read," the notification's `readStatus` should be updated to true for that user.
- [x] When a user selects `Delete Notification`, the notification should be removed and no longer displayed in the notification list.
- [x] In the three-dot menu, selecting `Enable notifications` should activate the notification for the user.
- [x] In the three-dot menu, selecting `Notification Settings` should redirect the user to the Notifications tab within the Profile section. This is handled in this [PR](https://github.com/Aam-Digital/ndb-core/pull/2712).
- [x] When the user clicks on the notification then the user will be redirect to the corresponding notification action URL.
- [x] When a user marks a notification as read or deletes it, the unread notification count should be updated accordingly.

**Comment by Ayush8923** [comment]
> Is an event record specific for a single user or are these "global" events, that are viewed by all users who have activated that type of notification?

As far as I understand, event records are user-specific. Each user will have the ability to select the types of notifications they wish to receive. A new sidebar tab will be introduced, allowing users to define their preferences for different event types. From this tab, users can opt-in to notifications for specific event types, ensuring they are only notified about the events they have selected.

In the CouchDB user document, we can to add the following fields to manage this customization:
1. **notificationsEnabled:** A boolean field indicating whether the user has enabled notifications.
2. **enabledNotificationTypes:** An array field listing the event types for which the user has chosen to receive notifications.

@sleidig @tomwwinter Please let me know what you think/suggest?

**Comment by Ayush8923** [comment]
> > Is an event record specific for a single user or are these "global" events, that are viewed by all users who have activated that type of notification?
> 
> As far as I understand, event records are user-specific. Each user will have the ability to select the types of notifications they wish to receive. A new sidebar tab will be introduced, allowing users to define their preferences for different event types. From this tab, users can opt-in to notifications for specific event types, ensuring they are only notified about the events they have selected.
> 
> In the CouchDB user document, we can to add the following fields to manage this customization:
> 
> 1. **notificationsEnabled:** A boolean field indicating whether the user has enabled notifications.
> 2. **enabledNotificationTypes:** An array field listing the event types for which the user has chosen to receive notifications.
> 
> @sleidig @tomwwinter Please let me know what you think/suggest?

Here's an updated schema and approach for updating an existing CouchDB user document to include the new keys `notificationsEnabled` and `enabledNotificationTypes`.
```
{
  "_id": "User:Anilaabh",
  "_rev": "2-f9e14ee88f8107bd3a7bd5ec82f40fa4",
  "name": "Anilaabh",
  "paginatorSettingsPageSize": {},
  "created": {
    "at": "2024-01-08T17:45:16.529Z",
    "by": "User:demo"
  },
  "updated": {
    "at": "2024-01-08T17:45:16.529Z",
    "by": "User:demo"
  },
  "notificationsEnabled": true // This is the boolean field indicating whether the user has enabled the notifications or not.
  "enabledNotificationTypes": ["childer", "school"] // This is the event types field for which types of the event the user have chosen to receive the notification.
  "phone": "+919546945162"
}
```

**Comment by Ayush8923** [comment]
@sleidig We need to update the user document to include `userNotificationsEnabled`(This is used to check whether the user has enabled notifications for the app) or `userNotificationTypes`(which types of notifications does the user need), but as far as I can check, we don't have a file for the user database entity. Should we create a new user database entity file for this, or is there another way to update the user document in CouchDB?

**Comment by sleidig** [comment]
I think this can become a part of the NotificationConfig entity that you outlined here: https://github.com/Aam-Digital/ndb-core/issues/2723 ?

**Comment by Ayush8923** [comment]
Yes this is part of the `NotificationConfig` entity, we can use the same database schema for saving/updating the `userNotificationsEnabled` value.
