### ISSUE TITLE
Missing 'Select Entity Type' Dropdown in Public Forms and Export Templates

### ISSUE THREAD

**Issue by Abhinegi2** [Aam-Digital/ndb-core#2739]
**Describe the bug**
The Select Entity Type dropdown is not visible in Public Forms and Export Templates.

**To Reproduce**
Start Application locally
1. Navigate to Admin → Admin Overview.
2. Open Manage Export Templates.
3. Open Manage Public Forms.

**Expected behavior**
The Select Entity Type dropdown should be visible in both sections, allowing the user to select an entity and input data as needed.

**Screenshots**
<img width="1309" alt="image" src="https://github.com/user-attachments/assets/fab0e853-ec55-47d4-87b7-d778bb591376" />

**Additional context**
This error is currently showing in the developer tools-
 `sentry-angular.mjs:162 TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'FormGroup'
    |     property 'controls' -> object with constructor 'Object'
    |     property 'route' -> object with constructor 'FormControl'
    --- property '_parent' closes the circle
    at JSON.stringify (<anonymous>)
    at dynamic-component.directive.ts:52:61
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:17)
    at _next (asyncToGenerator.js:17:9)
    at asyncToGenerator.js:22:7
    at ZoneAwarePromise (zone.js:2702:25)
    at asyncToGenerator.js:14:12
    at DynamicComponentDirective.loadDynamicComponent (dynamic-component.directive.ts:69:41)
    at DynamicComponentDirective.ngOnChanges (dynamic-component.directive.ts:37:17)`

**Comment by Ayush8923** [comment]
@sleidig  As far as I and @Abhinegi2 have checked, this issue was present earlier in the local system. However, when we tried to replicate it now, we were unable to reproduce it. We also verified this issue on the dev site, demo sites, and the latest PR deployment, and it is no longer present.

**Comment by Abhinegi2** [comment]
@Ayush8923 I found the issue. It's caused by the entity configuration saved in CouchDB.

Previously, the Public Form configuration was stored in the database like this:
```
"entity": {
  "label": "Entity",
  "editComponent": "EditEntityTypeDropdown",
  "dataType": "string"
}
```
However, since we updated the entity type dropdown to use "editComponent": `EditEntityType`, and it's not getting updated in the local db that's why it's no longer visible in the UI.

@Sleidig, I just wanted to confirm: is this scenario possible in production, or is it specific to the local environment?

**Comment by sleidig** [comment]
Thanks guys for reporting and investigating this :heart: 

The entity config for this internal type should usually not be in the DB (so that we _can_ reliably update it through the code base). But I think we are not preventing users to try and change the type (and thereby save it to the DB) yet. We should maybe add a flag to Entity classes to mark them as "users are not allowed to edit this entity type" (something like a `static fixedInternalEntityType: boolean`) and then remove the "edit data structure" options

**Comment by Abhinegi2** [comment]
I think it was added to the DB because we are directly using editComponent in our `@DatabaseField()entity`. 
That’s why it was saved in the entity config. 

- To manage it through the codebase, should we add this editComponent to our module file(PublicFormModule)?
