### ISSUE TITLE
write instructions how to use compodoc in wiki

### ISSUE THREAD

**Issue by Lorsbyjm** [Aam-Digital/ndb-core#276]

**Comment by sleidig** [comment]
Are you thinking to put this into the GitHub Wiki or the "developer wiki" in our compodoc docs? I would prefer to have everything in one place, in the compodoc docs. Maybe infos about compodoc would fit into the "Contribution Guidelines" section? (actually, it looks like it's partially already there)

**Comment by Lorsbyjm** [comment]
@vlle1  did you already do that? that just close this issue ;)

**Comment by vlle1** [comment]
see compodoc_sources/guidelines/documentation.md
