### ISSUE TITLE
transfer as much as possible from /doc/technical to markdown

### ISSUE THREAD

**Issue by Lorsbyjm** [Aam-Digital/ndb-core#279]
transfer as much as possible from /doc/technical to markdown (/doc/compodoc_sources)

ask @vlle1 for more information

**Comment by vlle1** [comment]
I've added the graphics and markdown files as written above.
the only files left can be found (branch compodoc) under doc/unused.
I don't consider them really important because the new documentation has a better representation of the project structure.
