### ISSUE TITLE
create tutorial files or other 

### ISSUE THREAD

**Issue by Lorsbyjm** [Aam-Digital/ndb-core#282]
(see https://www.divio.com/blog/documentation/)

**Comment by sleidig** [comment]
I'll be happy to help writing tutorials. If you have a general format for tutorials and/or a list of topics feel free to assign me some of them.

Nice article about documentation, by the way!

**Comment by sleidig** [comment]
Maybe we can even set up some interactive tutorials of how to get started and how to create your own entity type, etc: https://www.katacoda.com/create

**Comment by Lorsbyjm** [comment]
Yeah, that would be nice, but I will not put in the Todo List for october.
