### ISSUE TITLE
structure of compodoc (discussion)

### ISSUE THREAD

**Issue by vlle1** [Aam-Digital/ndb-core#293]
If we want to keep working with compodoc, we *have to get along with the current menu*. we can only discuss the structure/name of section "developer wiki". If this order is too clumpsy or irritating, we should consider either building a similar file structure on our own (huge effort) or sticking with the old wiki and restructure the articles there.

~~changing the structure of the compodoc is possible via the config file of a compodoc - see
https://compodoc.app/guides/tab-configuration.html~~
this feature only makes it possible to change the structure of the tabs inside of a page (e.g. to swap between API, Source and DOM Tree). Concentrating auto-generated sections into top-level entry "Reference" is not possible that way.

everyone is invited to express their wishes in favour of a better structure of the compodoc (if you haven't seen it yet, here it is :http://aam-digital.github.io/ndb-core/

this is the current idea of structure by @sleidig :
- split up "developer wiki" into seperate sections
- concentrate auto-generated sections into top-level entry "Reference"
- inspiration: https://angular.io/docs
> I'd suggest to rename the compodoc section "developer wiki" to avoid confusions between that and the GitHub Wiki. Maybe the "developer wiki" section should actually become three sections (following https://www.divio.com/blog/documentation/): "Tutorials", "How Tos" and "Explanations" (maybe there are better titles for them). [...]
Is it possible to move the generate sections (Modules, Classes, Injectables, Guards, Interfaces, Miscellaneous, Documentation Coverage) under a top-level menu entry called "Reference" (or a similar name)?
I kinda like the Angular docs, maybe their structure can also be some inspiration for us? (Tutorial, Fundamentals, Techniques, API/Reference (https://angular.io/docs)

- Note: after restructuring I will also delete the old duplicate wiki files (I just want to get the compodoc to work properly first ;)

**Comment by vlle1** [comment]
I decided to rename the section to developer manual.
It will be split up into tutorials, how to's, explanation and reference. Further splitting isn't needed right now and leads rather to confusion than to a clear structure.

**Comment by sleidig** [comment]
@vlle1: also have a look at issue #15 and close it if you consider it somewhat covered with our new docs.

**Comment by vlle1** [comment]
We (/I) decided that the structure of the documentation is ok right no, it would be too much effort to change things a lot (messing with compodoc), that is not our priority right now.
