### ISSUE TITLE
! Saving of Child broken - Bad special document member: _child (500)

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#302]
When trying to save a Child Entity (with CouchDB database, not the temporary in-memory database) an error is logged and saving is not possible:

> Bad special document member: _child (500)

**Comment by codingfabi** [comment]
I just merged @TheSlimvReal's hotfix to the master.
@sleidig can you confirm that everything works fine again now?

**Comment by sleidig** [comment]
I assume you can confirm that, as you merged ;-)

I have found another related bug:

1. Edit a Child's name
2. Press "Save"
3. The changed entity gets saved
4. but in the form of the still open details page, the name switches back to the previous value

**Comment by sleidig** [comment]
It seems that the changes are getting display, however only after some delay during which the old values are displayed again. How can this be avoided?

**Comment by sleidig** [comment]
also see #316
