### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by RichardNutt** [Aam-Digital/ndb-core#304]
When trying to log in on the master branch, I'm getting the following errors:
`OPTIONS https://demo.aam-digital.com/db/_session 405`
`Access to XMLHttpRequest at 'https://demo.aam-digital.com/db/_session' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
`Failed to connect to the remote database: [object Object]`

Accessing with chromium using the disable-websecurity-flag works.
![Screenshot](https://user-images.githubusercontent.com/18560153/60094870-7e5fe300-974d-11e9-857c-022f3cbc4bd5.png)

**Comment by RichardNutt** [comment]
There might have been an issue with the config file on my end. I can't reproduce this error at the moment.

**Comment by sleidig** [comment]
The server is not running very stable at the moment, maybe it was indeed unreachable for some minutes at that time. I'm working on moving everything to Kubernetes on Google Cloud, hopefully that will improve things also

**Comment by RichardNutt** [comment]
The server was definitely up at the time, since I was able to reach it when ignoring CORS-policies.

**Comment by RichardNutt** [comment]
can't reproduce the error anymore...
