### ISSUE TITLE
Research privacy & data protection standards and requirements

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#313]
We should research and step by step implement all requirements of high privacy and data protection standards - especially with regard to GDPR.

**Comment by codingfabi** [comment]
Maybe we could find some help inside de EWB-Organisation? They had to rework their data privacy and protection rules a few months ago. They may not know about detailed technical stuff like encrypton or similar, but they may be able to help us with sources. @Lorsbyjm what do you think? do you know who was responsible back then?

**Comment by sleidig** [comment]
Interesting input regarding this also: https://blog.holisticon.de/2018/09/gdpr-no-data-to-the-rescue/

**Comment by Lorsbyjm** [comment]
Concerning sources we might ask Andi and Manon, they managed the whole DSGVO process.

**Comment by sleidig** [comment]
this is in progress in our non-technical task / project management tool. Any technical and operational measures required in the app will be added as their own issues and assigned a common label or milestone.
