### ISSUE TITLE
Validation of child attributes when saving

### ISSUE THREAD

**Issue by Lorsbyjm** [Aam-Digital/ndb-core#324]
Right now there is no validation and every value can be empty. It is nicer if there are some required attributes (at least in the frontend) like name, date of birth ...

**Comment by codingfabi** [comment]
I implemented some validations in the branch ChildSavingStatusAndFormValidation and opened a PR for it. Please add some comments on the PR if we need more validation with the form.

**Comment by codingfabi** [comment]
Should we implement a saving notification for other entitys aswell? we could implement the alert service into the basic entity save method in the EntityManagerService...

Thoughts @sleidig @liwde @TheSlimvReal ?

**Comment by liwde** [comment]
Hm. In principle, I'd say yes, validation might be useful in a central place. Maybe there is already something in the EntitySchemaService, that allows annotating restrictions on certain fields of an entity?

However, you bring this already into the form that doesn't necessarily "know" about the entity. And this is absolutely the right thing, as then Angular can handle most of the validation without needing to go to the entity. So: thinking about it in a central place is good, but we'd still need to implement it everywhere else in the forms as well -- at least that is what I'm thinking...

**Comment by sleidig** [comment]
I am a big fan of a generalized solution. But we shouldn't mix the data/logic oriented services with the UI providing alerts to users. Maybe slowly we can work towards a generic component as the base for all forms (ChildDetails, SchoolDetails, ...) that includes something like this?

Also, from a UX perspective form field validation with an error message at each field would be awesome in the long run (see [live example](https://angular.io/generated/live-examples/form-validation/stackblitz.html) from the [Angular Docs](https://angular.io/guide/form-validation))
