### ISSUE TITLE
Remove empty language filter in School List filter panel

### ISSUE THREAD

**Issue by Lorsbyjm** [Aam-Digital/ndb-core#326]
The filter for languages has one empty element, this could be deleted.
~~Furthermore the langue should always be englisch (Deutsch -> German)~~

![image](https://user-images.githubusercontent.com/9371498/61896809-033d4880-af16-11e9-8ce0-f9cffb042671.png)

**Comment by sleidig** [comment]
I think the filter use dynamically generated from the data. So it's probably just a matter of changing the child details of existing entities?
