### ISSUE TITLE
Saving new note has no visible reaction

### ISSUE THREAD

**Issue by Lorsbyjm** [Aam-Digital/ndb-core#328]
If you create a new note an click save the note is not displayed in the list. If you leave the section and come back the note is shown. Should trigger a reaload after saving a new issue ?!

**Comment by sleidig** [comment]
Confirmed. This is a bug and has to be fixed. If we can, avoiding a complete reload would be nice as the production systems can have a lot of Notes, leading to noticeable loading times.
