### ISSUE TITLE
Dashboard/Notes broken on mobile

### ISSUE THREAD

**Issue by RichardNutt** [Aam-Digital/ndb-core#351]
Opening the dashboard or notes from a different tab (e.g. Children) results in a grey overlay and the app stops taking inputs on the dashboard/note tab (e.g. scrolling, selecting/editing notes).

![Peek 2019-10-14 17-11](https://user-images.githubusercontent.com/18560153/66762483-5b953e00-eea6-11e9-9fe6-b8ca30a95d0e.gif)

Might be related to acfe705438d19f8115392cb6b3573726bbe5c21e.

**Comment by sleidig** [comment]
I couldn't reproduce the bug. Which OS and Browser are you using?
Opening the "Notes" section takes really long to load but then finally it is showing for me as expected without overlay.

In any way, with the demo data performance shortfall is becoming noticable even with the in-memory database. We should definitely start using pagination for Notes and similar views.

**Comment by RichardNutt** [comment]
Linux 5.3.5-1-MANJARO und Opera 64.0.3417.47. Ich werde es mal mit anderen Browsern versuchen.

**Comment by RichardNutt** [comment]
My bad. I accidentally was on the blob-service branch. This issue does not exist on the master branch.
