### ISSUE TITLE
Overview of BMI (height&weight) as a children list

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#354]
As a social worker I need to follow up with all children who are malnourished, identified by a low/high BMI. For this I need to list all affected children to see them at a glance.
At the moment each child's height&weight is visible form its individual details page but there is no overall list from which to get an overview.

**Comment by Lorsbyjm** [comment]
Hi @sleidig, @TheSlimvReal just took me a bit to understand the new design completely defined in the config files. 
The BMI is computed based on height and weight and no database field. Therfore following need to be done:
- [ ] ceate a new BMI table component
   - weight and height are not stored in the child entity. Call the newest health check entry. 
- [ ] add the BMI in the configuration file

**Comment by sleidig** [comment]
welcome back @Lorsbyjm :smiley: 
The documentation around the config system is a work in progress, sorry about that.

This sounds like a good overview of the tasks. I guess the key parts are loading the latest health check entries and designing to table view. Developing the view component might be easier in isolation using storybook, I'm happy to help anyone getting started with that if necessary.

**Comment by Lorsbyjm** [comment]
Hey,@sleidig . I added a component and changed the config file, but I cannot load Health information from the database. 

 this.childrenService
        .getHealthChecksOfChild(this.child.getId())
        .pipe(untilDestroyed(this))
        .subscribe((results) => {this.records = results
       //   .sort(
       //   (a, b) =>
       //     (b.date ? b.date.valueOf() : 0) - (a.date ? a.date.valueOf() : 0)
       // );
      });
      console.log(this.records)

always returns an empty array. 
If selecting a child the panel there is full.

**Comment by sleidig** [comment]
is there an effect when you omit `.pipe(untilDestroyed(this))`?

Please push a code sample in a draft pull request, then I can have a look at the exact context

**Comment by Lorsbyjm** [comment]
Already solved the problem with @TheSlimvReal ;)

**Comment by TheSlimvReal** [comment]
How about creating a dashboard widget for this feature?
