### ISSUE TITLE
create backup script

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#355]
the production instances are run using docker-compose as two docker containers - a modified nginx containing the app and a standard couchdb. We need a reliable backup script that either saves the volume containing the couchdb files or uses couchdb's replication. The backups should keep a few copies (maybe one for each day of the last 10 days) and automatically delete outdated backups.
To make this easily deployable, maybe we can create another docker image for running these backups as cronjob that can simply be included in the docker-compose file.

**Goal:**
* a single script that creates a full backup
* a single script that restores from a backup
* ideally these scripts are packaged into a docker image for easy deployment that automatically runs for the deployment without additional configuration

**Tasks on completion:**
* deploy the backup routine and test it
* set up a process that copies the backed up files to a separate server to make them available in case the server becomes completely corrupted

**Comment by sleidig** [comment]
I am sure there are solutions out there already. But we still need to at least set up and configure this.

**Comment by Ma27** [comment]
How about using [borgbackup](https://borgbackup.readthedocs.io/en/stable/) with some kind of timer functionality? I'm pretty sure that there some fully-working solutions out there that shouldn't be too hard to use :)

**Comment by sleidig** [comment]
Yes, borgbackup looks nice. That certainly can be scheduled.
Can you also look into how we could use this if we later on run on Kubernetes on a platform like cloud.google.com?

**Comment by Ma27** [comment]
Just a short update: in today's session I bootstrapped the docker-based setup (it took me a while though to figure what needed to be done and I thought that it might be useful for other people to simplify the setup which is what I'm currently working on).

As soon as this is done (probably next Tuesday :)), I'll continue working on the backup script :)

**Comment by sleidig** [comment]
possibly interesting: https://restic.net/

**Comment by sleidig** [comment]
is this still relevant @TheSlimvReal ? I guess our incremental backup of the folders does a sufficient job? Feel free to close this here.

**Comment by TheSlimvReal** [comment]
Yes I also think we have quite a good backup setup.
