### ISSUE TITLE
setup to run on Kubernetes

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#356]
Create the required configuration and documentation to run the Aam Digital docker containers on a Kubernetes cluster to benefit from the scaling, monitoring and other tooling of Kubernetes.

We are currently running our app using docker with a _docker-compose_ file. This works well and with some initial manual steps allows us to start new instances for other users. To improve the stability and scalability we should move from our self-administered virtual server to a Kubernetes-based cloud platform, however. Google Cloud Platform seems best suited for our basic needs. Kubernetes also integrates with many useful tools for monitoring and configuration that we could benefit from by running our docker containers inside Kubernetes.

**Tasks:**
* create Kubernetes configuration files to run instances of our app on Kubernetes (with the same functionality as the current docker-compose setup)
* documentation about how to use and tweak the Kubernetes configuration

further tasks for later:
* script to spin up a fresh instance including initial database setup, etc.

**Comment by TheSlimvReal** [comment]
Is there already a plan where the kubernetes will run once its ready to go live?

**Comment by sleidig** [comment]
I opened a test account for Google Cloud Platform some time ago (although I didn't get very far). Their pricing seems best suited for our small scale project to me. As Kubernetes is available by many providers it should be fairly easy to switch, however.

**Comment by sleidig** [comment]
not relevant at this time
