### ISSUE TITLE
AAM-Digital Logo

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#364]
It's about time to create a Logo for our project group.
This logo could also be used to make some stickers and flyers.

**Comment by TheSlimvReal** [comment]
Feel free to comment some ideas or logo drafts

**Comment by codingfabi** [comment]
We could consider hiring someone on Fiverr for a logo design. This would cost about 30€ for a professional logo. I would prefer this over using our own photoshop skills. Thoughts?

**Comment by sleidig** [comment]
we could certainly invest some money into a good logo. But I think we probably need to define a general idea and context as guidelines to get a design that meaningfully represents our project. I am not sure about the general direction for a logo yet. Any ideas?

**Comment by vlle1** [comment]
I am currently working on the logo.
Todo: provide different versions (quadratic,...)
