### ISSUE TITLE
user-defined, sortable groups for roll call

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#369]
*As a teacher/socialworker I want to define my own groups of children in order to efficiently take attendance of a certain group that attends my class or center without having to skip over a lot of other students.*

**Objective**
While our app has a filter for the daily attendance / roll call feature (you can display children for a certain center or for a specific school) this is not flexible enough. Often class is attended by a group of students from several schools but not by all students of the center.
Users should be able to create custom groups of students and select from these when starting to take a day's attendance.

**Proposed Solutions & Alternatives**
* children group management view to select certain children, create and save a new group or edit an existing group
* daily attendance to allow selecting from the children groups (in addition to centers and schools as possible filters?)

> As this is a larger, critical feature the design (technical and UX) should be discussed within the team early for feedback.

**Further ideas for extension in the future**
* maybe an option to save shortcuts to "favourite groups" linked to the user account so that a user can very quickly jump to the daily attendance for his class of students.

**Comment by TheSlimvReal** [comment]
So you don't want to directly link the groups with the user but only make a soft link where each user might have a number of most used groups?

**Comment by sleidig** [comment]
I think there is use for "global" groups shared between users (e.g. a list of students who are part of a specific programme for which different staff members have to take attendance). This is why my suggestion is to have user-independent group definitions and "soft links" to these that each user can customize.

**Comment by sleidig** [comment]
also see #332 for UI improvements to be considered related to this.

**Comment by sleidig** [comment]
With the introduction of recurring "activities" and broader changes in our attendance system this use case will also be covered.

see #497
