### ISSUE TITLE
use mat-datepicker for all date fields

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#370]
Some of our forms that include date fields already use the mat-datepicker component (e.g. the Date of Birth in the ChildDetailsComponent), which offers a nice popup to select the date. Other forms do not use this yet and should be changed to make use of the mat-datepicker:
* NoteDetailsComponent
* SubrecordEntityComponent
* Child School Relations (popup when editing lines of the Education section in ChildDetails)
* Health section of ChildDetails
* DropoutDate of ChildDetails
* Attendance Register filters
* Add Daily Attendance

**Comment by TheSlimvReal** [comment]
Got merged with #395
