### ISSUE TITLE
Deleting Notes

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#371]
At the moment a Note cannot be deleted from its Detail view (the popup form) because we don't display a delete button.
On the other hand we do have a delete button in the EntitySubrecordComponent, the table that displays all Notes of the child in the ChildDetails. However that would delete the whole Note very easily even if that Note is linked to more than just this child.

Also, from a general perspective we do not want users to delete old Notes - these should be kept as an archive. There are cases - like accidentally adding a Note - where the option to delete is necessary, however.

We should carefully think about the UX in these cases to find a consistent approach that avoids accidental data loss and doesn't frustrate users searching for a delete action.

**Comment by TheSlimvReal** [comment]
How about saving the last 10 deleted entities which can be recovered from a separate screen?

**Comment by sleidig** [comment]
To make this possible but not too prominent, I would suggest to add a three-dots menu next to the save and cancel buttons in the Note Details and put the delete option only in that context menu.

![image](https://user-images.githubusercontent.com/1682541/114573397-a39e4800-9c78-11eb-8e65-c898328521ed.png)
https://material.angular.io/components/menu/examples
