### ISSUE TITLE
Add paginatior for big tables

### ISSUE THREAD

**Issue by Schottkyc137** [Aam-Digital/ndb-core#381]
At the moment, big tables used in, for example, the notes-manager or the children-list display every single element in a big scroll view at once. 
In my opinion, a better user experience can be achieved using a paginator that displays the entries throughout different pages. The first test of this has also shown better performance since not every entry has to be loaded and rendered at once. 

Personally, I do not know how those entries are being used in a temporal context. However, I can imagine that the working set might only include a few months of entries. If this is the case, and the database allows it, it might be a good idea in a second step to only load a few months worths of data and then load more if needed.

**Comment by sleidig** [comment]
I am also in favour of paginated lists where the number of elements is really large. To help performance, this should not just be a UI change but actual load only part of the entities from the database (however, these need to be in the required order).

**Comment by sleidig** [comment]
These long lists without pagination have become a big problem for performance (and thereby for usability). Assigning this high priority.
