### ISSUE TITLE
Use prettier with pre commit hooks

### ISSUE THREAD

**Issue by codingfabi** [Aam-Digital/ndb-core#396]
@TheSlimvReal and me discussed using a tool to guarantee lint-confirm code. 
I got some experience working with [prettier](https://prettier.io/) and would volunteer to do a setup for our project. But I wanted to hear your thoughts about adding pre commit hooks and forcing contributers into a certain code format?

**Comment by codingfabi** [comment]
For those who are further interessted:

Prettier can be used with or without pre-commit Hooks. 
If would only be usefull to implement it with a pre-commit tool like [husky](https://github.com/typicode/husky). 
Then, prettier automatically fixes your tsLint warnings and formats your code. For example, adding missing semicolons or replacing double with single quotes. It can also arrange html tags and removes trailing whitesspaces etc. 

I think it could save us a lot of time because it could prevent us from fixing broken CI - Tests that only fail because of linting errors.

**Comment by sleidig** [comment]
This sounds cool. Additionally a pre-commit hook could warn if there are linting errors that cannot be fixed automatically (if that even exists).
