### ISSUE TITLE
"Previous Schools": display class and grade percentage

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#398]
The "Previous Schools" table in the "Education" section of the Child Details should manage the class and results for each line as well.

- "class" (string) -> which class/grade the student was attending at that school and time
- "results" (float) -> total marksheet average results (in India usually displayed as a percentage, e.g. he scored 78% in class 10 exams)

Both should be displayed and edited in the table similar to the columns that are already part of the table.

**Comment by Schottkyc137** [comment]
Is the result-field going to be a new field or can that be computed out of some other data?
Also, the previous schools are not editable, is that something that should be implemented as well?

**Comment by sleidig** [comment]
The results would be a simple input field for the time being. In the mid to long run it would be exciting to have a more detailed feature for grades down to the individual subject (something like a digital copy of the marksheet with all its details) but for that we first should draft possible UI layouts and plan it out. (feel free to think about that as well and propose something, however!)
