### ISSUE TITLE
New note not displayed when saving via the primary-action

### ISSUE THREAD

**Issue by Schottkyc137** [Aam-Digital/ndb-core#401]
When a new note is being created via the primary-action component while in the note-manager component, it is only visible after a reload.
I'm not sure what the best approach here is. A general solution could be to add the functionality to subscribe to the EntityMapperService in order to get notified when a new Entity is being saved which can then lead to a reload of the data.

**Comment by sleidig** [comment]
probably same cause as #554 , closing this issue as the newer one contains more information.
