### ISSUE TITLE
Implement EntitySchema Datatype "recursive" to consider annotations within referenced object

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#402]
For more complex Entity classes it would be helpful to recursively use schema annotations within referenced objects to control which properties of such an object will be written to the database.

For example:
```
class ComplexEntity extends Entity {
  @DatabaseField() title: string;
  @DatabaseField('recursive-schema') details: Description;
}

class Description {
  @DatabaseField() id: number;
  otherStuff: string; // won't be serialized to the database as it doesn't have the annotation
}
```
should result in a json object like this: `{ "title": "foo", "details": { "id": 123 } }`

---
* [ ] decide on a name for the "datatype" (e.g. "recursive-schema")
* [ ] write unit tests for all variations
* [ ] implement functionality

**Comment by TheSlimvReal** [comment]
Is this now done with #403 and can be closed?

**Comment by sleidig** [comment]
Yes, this is the thing
