### ISSUE TITLE
Maintain scroll level when navigating through the app

### ISSUE THREAD

**Issue by christophscheuing** [Aam-Digital/ndb-core#406]
**Describe the bug**
The scroll level for different parts/views/pages/components of the app seems to be general and not specific. This isn't very handy. It would be more intuitive to maintain the scroll level for every single view.

**To Reproduce**
1. In the app click on "Children" to see the "Children List", which is shown from the top.
2. Click on the first child in the children list to open the child details view.
3. Click on education to see the education details and scroll down to the bottom of the page.
4. On the left side click on "Children" again to go back to the children list. 

**Expected behavior**
The user would expect to get back to children list as she/he left it, meaning that when she/he was last viewing the children list at the very top, she/he should be brought back there.
However the children list is scrolled downwards to a certain extend. 

**Occurence**
As far as I have tested it, this behavior happens in all browser, even on mobile devices.

**Additional context**
Maintaining the scroll lever is probably a more general UI question, also regarding other components/views of the app. It would be nice to have individual scroll levels.

**Comment by christophscheuing** [comment]
This issue is broadly discussed in https://github.com/angular/angular/issues/24547
I've played around and tried the solutions provided there, but unfortunately I couldn't get it to work.
Anyone with a deeper understanding / more luck?

**Comment by sleidig** [comment]
can't reproduce this anymore after the ux redesign (#1086)
