### ISSUE TITLE
Child Details' Attendance tables overlap on smaller screens

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#413]
**Describe the bug**
Layout of the "Attendance" section in the Child Details Component is not responsive for smaller screens:
![image](https://user-images.githubusercontent.com/1682541/74272064-46be9f00-4d0e-11ea-80be-41a593bc909b.png)

**To Reproduce**
1. Click on a Child to open the Child Details view
2. Expand the section "Attendance"
3. Resize your window to see overlap of the two tables

**Comment by Lorsbyjm** [comment]
Problem solved. 
But I found that the calender and the table have fixed widths in some parts. We might want to change that? @sleidig If not, we can close the issue.

**Comment by sleidig** [comment]
It was a little difficult to get a nice and consistent layout with different text in the calendar day boxes, so that was a process of trial and error. If we can manage it with relative measures that would be great. Do you wanna have a look?

To reduce the delay in our PRs I am still merging your fix now.
