### ISSUE TITLE
Add PWA functionality for mobile devices

### ISSUE THREAD

**Issue by christophscheuing** [Aam-Digital/ndb-core#418]
*As a user of a mobile device I want to be able to use the AAM-App just like a native Android / iOS app.*
This would provide a better user experience compared to opening the AAM-website within a mobile browsser.

**Objectives**
- enhancing user experience
- facilitating offline usage
- further more ...

**Proposed Solutions & Alternatives**
Making use of the PWA standard (by providing a valid mainfest etc.) would allow the app to be installed to the home screen of the mobile device and thus appear like a native mobile app. 
Incorporating and correctly configuring service workers would allow us to control the offline usage in case of lack of an internet connection.
A splash screen when opening and loading the app would be a nice design feature.

**Additional context**
Since Chrome allows installing PWAs also on desktop computers, this would allow the AAM-app to be installed and used similarly to a native standalone app on Windows, Linux and MacOS. If this is desirable of if opening the app in the browser on desktop machines appears as the betters solution, remains to be discussed.

**Comment by sleidig** [comment]
I am quite sure this had been working previously - but indeed I am facing problems with these aspects now. Should be checked and fixed :+1:

**Comment by sleidig** [comment]
fixed in PR #441
