### ISSUE TITLE
Usernames should not be case sensitive

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#459]
Currently, login is only possible if the user enters the username in exact capitalization (e.g. "Demo" and "demo" would be two different user accounts). That is not intuitive. Should we accept any capitalization of usernames?

Also: automatically trim spaces from username and password to avoid mistakes from copy&paste.

**Comment by christophscheuing** [comment]
I'd say it is OK for the username to be case sensitive. Usernames often are and I don't find this to be very unintuitive.
But on the other hand, what disadvantage would it have to make to username to be not case sensitive? This shouldn't be hard to implement and so far we probably don't have many usernames that only differ in small or capital letters.
Of course we should take care that the check if a username already exists when creating a new user is also not case sensitive.

**Comment by sleidig** [comment]
As we are switching to a more sophisticated user authentication service (Keycloak, see #1340), I am closing this issue here. We should revisit what username / email is feasible and easy to use and supported by Keycloak.

**Comment by TheSlimvReal** [comment]
For keycloak the case (in-)sensitivity is not a problem at all, we can even allow users to optionally log in using their email instead of a normal username. 
The question is what we store for local/offline authentication (probably what the user entered as name - potentially in lower case)

**Comment by sleidig** [comment]
great. Yes, I think it probably makes sense to normalize what we use offline - either all caps or all lower case - to make that more resilient as well.
