### ISSUE TITLE
Move health and dropout form fields to separate component

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#499]
On the `child-details` view in the submenu `health` and `dropout`, there exist some form fields which display and modify attributes of the child entity. These form fields should be moved to a separate component.

Steps to do for the `health` and the `dropout` form

- [ ] Create a new component which receives as input the `Child` object
- [ ] Rebuild the form in the newly created component
- [ ] Add `edit` and `save` buttons
- [ ] Replace the form in the `child-details` submenu with the new component

**Comment by sleidig** [comment]
I would maybe move the "dropout" information to the main "basic information" of the child entity itself. This is from the use case really part of the core child information. We can hide these fields completely and only show them in the top section if the status is set to dropout.

**Comment by TheSlimvReal** [comment]
> 
> 
> I would maybe move the "dropout" information to the main "basic information" of the child entity itself. This is from the use case really part of the core child information. We can hide these fields completely and only show them in the top section if the status is set 

We came to a new solution where we keep the health and dropout information on the child entity, but allow each attribute to come with a flag whether it is shown in the basic information or not.

**Comment by sleidig** [comment]
done in PR #508
