### ISSUE TITLE
Evaluate whether all components in child detail view only need the child

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#500]
The submenu in the `child-details` view should be configurable by the final user. Optimally the user only needs to provide the name of the subfolder and the component which is displayed in this subfolder. The best case would be, that each of the components that can be selected, only needs the `Child` object as input parameter. This would allow the components to be very reusable and the configuration of the `child-details` view to be very simple.

Steps to do:

- [x] Check which components already only need the `Child` object as input
- [x] Create strategies for the other components, so they are only dependent on the `Child` object
- [x] Create an issue for each component that needs to be changed

_relates to #222_

**Comment by sleidig** [comment]
done in PR #508
