### ISSUE TITLE
Build menu from a configuration object

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#501]
The top level menu is already very dynamic in its creation. For each button, a menu item is added in the `app.module.ts`. This process should be automated. The input will be an array of configuration objects and for each of these objects, a menu button will be added.
The configuration objects should **at least** consist of the `name` of the menu button, the `icon` which will be displayed next to the name and the `component` to which this button links.

Steps to do:
- [x] Create a structure for the configuration object
- [x] Create a function which gets an array of configuration objects and creates an menu button for each object
- [x] Replace old procedure by this new one
- [x] Write tests for these methods
- [x] Optional: Also create routes and guards from the same configuration object (`app.routing.ts`)

_relates to #222_

**Comment by sleidig** [comment]
done with #510 / #504
