### ISSUE TITLE
Month not visible when editing monthly attendance on child details view

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#505]
**Describe the bug**
In the child details view in the attendance section, the monthly attendance can be seen and edited. Clicking one of the monthly attendance records opens a popup with information about the attendance in this month. However, in this popup the month field is empty and needs to be refilled if a change wants to be done.

**To Reproduce**
1. Go to the child details view of a child
2. Open the attendance subsection
3. Click in the list on one of the monthly attendances
4. The month field should be empty and the attendance can't be saved until it is filled with a new month

**Expected behavior**
The month field should be filled with the correct month

**Comment by RichardNutt** [comment]
can't reproduce
![Peek 2020-11-24 19-48](https://user-images.githubusercontent.com/18560153/100138317-25d6cd00-2e8e-11eb-8e7b-cd58f4bcea81.gif)

**Comment by TheSlimvReal** [comment]
Happens on Firefox, does not happen on Chrome/Opera.

**Comment by RichardNutt** [comment]
related Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=888320

**Comment by sleidig** [comment]
with the new event attendance implementation monthly attendance summaries are generated and month is not editable, so this doesn't apply anymore.
