### ISSUE TITLE
Get filter options for list components from config

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#512]
The available filters for the `child-list` and the `school-list` components should be loaded from the configuration file. The config should define how the filter is called and for which values it filters. In the list component this config should be used to create the correct filters and display them as it is currently done. The view of the component should be the same as before.
A problem might be filters which use a function. This might be a question that can be discussed in the whole team. 

- [ ] Figure out structure for filter configuration in the `child-list` / `school-list` config object
- [ ] Create config for all the currently available filters
- [ ] Write a function which reads the filter config from the config file and creates the filters
- [ ] Remove hard coded filters from the list components

**Comment by sleidig** [comment]
completed with #550
