### ISSUE TITLE
Delete connected entities

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#547]
We provide the functionality to delete entities like children or schools.
However, we did not implement anything to delete or alter connected entities.

For example if a `Child` is deleted, there are still `ChildSchoolRelations` that are connected with this child which are not deleted.
This can cause problems in this case in the `SchoolDetails` component when all children attending this school are loaded.

We should think of a concept which also handles connected entities. One approach would be to delete them as well.

**Comment by sleidig** [comment]
Duplicate of #220 - for things like ChildSchoolRelation there is definitely a need for this, though.
