### ISSUE TITLE
Students overview in School Details empty on direct access in demo mode

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#548]
**Describe the bug**
When opening `SchoolDetails` without prior to that visiting 'Dashboard' or 'Children' results in an empty students list for this school. This probably happens, because the function to load the attending children uses the children service. Because the children service is in this case used the first time, the queries might not have been set up yet (this happens asynchron). A better solution would be to create a query outside of the children service (maybe the component which displays the attending students) which allows a more efficient retrieval of the data and deletes the dependency to the children service.

**To Reproduce**
1. Go to 'Schools'
2. Reload the page so this time you don not start on the dashboard but on the list of schools
3. Click on a school
4. The students table should be empty
5. Click on 'Children'
6. Click on 'Schools'
7. Open the same school as before
8. The students table should now be filled

**Expected behavior**
The list of attending students should always be loaded correctly

**Comment by sleidig** [comment]
Confirmed :+1: 

However, this bug also happens in the demo mode which doesn't rely on db indices. So I think there must be another cause behind it. Probably needs somebody to debug this in detail using breakpoints.

**Comment by sleidig** [comment]
Cannot reproduce this bug anymore
