### ISSUE TITLE
Notes are not added directly

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#554]
**Describe the bug**
The notes manager component allows to add new notes with a popup dialog.
The notes manager adds the note to the list of notes if it is returned when the dialog is closed.
This works if the `save` button is clicked in the first popup.
The `FormDialogService` opens a second popup if the first popup was closed by a click outside of the popup.
This second popup also allows to save the note.
However, when this is done, the notes manager is **not** notified about the saving of the note and can therefore not add the note to the list.
This results in the note not directly being visible in the list of notes.

**To Reproduce**
1. Go to 'Notes'
2. Click on 'add note'
3. Change some fields
4. Click outside of the popup
5. The popup should close and a new one should open which asks you if you want so save the entity
6. Click on 'save'
7. The saved entity is node visible in the list of notes

**Expected behavior**
The newly saved entity should directly be visible in the list of notes.

**Comment by sleidig** [comment]
also see #401 - same problem occurs through the primary action (in general, the list is not refreshed)
