### ISSUE TITLE
Save config in the database (or deploy config)

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#558]
The individual configuration for an instance of a single customer should be easy to switch and update - and not clog up our main core repository.

It could either be saved in a (separate, readonly) database or somehow managed as part of the deploy process.

**Comment by TheSlimvReal** [comment]
Moving the config to the DB sounds like the right way to later allow people to customize their UI from the app.
However for the beginning I like being able to edit the config file as a whole.
Therefore I suggest to create a section in the admin area where the config file can be uploaded and downloaded.
At the beginning a default config will be selected and can be replaced by uploading a new one

**Comment by TheSlimvReal** [comment]
Steps:

- [ ] Extend config service to save a config file into the db
- [ ] Extend config service to create a file from a config loaded from the db
- [ ] Create UI component in admin section do upload and download config
- [ ] Set fallback to a default config file
