### ISSUE TITLE
Allow EntityLists without ColumnGroup selection and only fixed columns

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#559]
Currently, the generic EntityListComponent requires to set a `columnGroup` config in the config-fix.json and always displays a toggle button group to select different column groups. For more simple use cases I want to display the list with just a fixed set of columns and not show any selection to the user.

Suggestion:

make the `columnGroup` object in the config completely optional. If it doesn't exist, just display all defined columns and hide the column group selection UI.

**Comment by TheSlimvReal** [comment]
I would not consider this very high priority. The column selection is not visible if only one column group is defined and the creation of a column group does not cost much time.
