### ISSUE TITLE
Replace fixed component maps with a service to dynamically register them

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#568]
Currently we are keeping a few hard-coded Maps of components that can be used in configurable parts of the app. To make adding components more straightforward, decouple the code and enable tree shaking to remove unused parts we should move towards a dynamic registration system, where each module calls a central service to register the components it provides. That gets us closer to a plugin like system where the core does not need to know about every single feature.

I think it is probably sufficient to just wrap the map in an Angular service and use that from different parts of the app?

Fixed maps currently:

- EntityDetails -> Entity map
- Router -> component map
- Dynamic Component map

**Comment by TheSlimvReal** [comment]
Maybe we could introduce a rule that modules in core are not allowed to have dependencies to other folders.

**Comment by sleidig** [comment]
> Maybe we could introduce a rule that modules in core are not allowed to have dependencies to other folders.

good point :+1:   there is even tooling supporting to enforce such constraints: https://nx.dev/latest/angular/workspace/structure/monorepo-tags
