### ISSUE TITLE
Add PWA Install button to our interface

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#592]
*As a user with limited computer experience I want to easily install Aam Digital "as an app" in order to allow me quickly find and open it everytime and make it feel like "a real app".*

**Objective**
As a Progressive Web App (PWA) our application can be install and look almost like a native app rather than like a simple website. However, multiple users have been unable to find the option in the browser to "install" the PWA or add it to their home screen. We should make this much easier to find. Also, every browser displays the option a bit differently, making it hard to guide users.

Ideally a user should be able to install the PWA with a single click.

**Proposed Solutions & Alternatives**
Add a button to the top or left menu / toolbar that always shows the option to install the pwa from within our own interface.

**Additional context**
https://web.dev/customize-install/

**Comment by sleidig** [comment]
some work and discussion had previously happened in this PR: #645 . May be useful to look over when picking this up again.

**Comment by christophscheuing** [comment]
Hint on how to test PWA functionality / service workers on localhost: https://stackoverflow.com/a/59785846
