### ISSUE TITLE
Generic Entity Display Components?

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#6]
> **Complex apps will have many similar views and should have an easy way to configure/extend from some base components.
> (e.g. "ChildList"/"SchoolList" or "ChildDetails"/"SchoolDetails" are rather similar)**

Currently, these are almost completely separate implementations.

Things to consider:
- Create small components that can be included and reused?
- Create a "generic Component" that can be extended or configured?

**Comment by sebastian-leidig** [comment]
First step is to implement a module in the sample app that creates some new Entity subtype and its views, see https://github.com/NGO-DB/ndb-sample/issues/3

**Comment by sleidig** [comment]
closing this in favor of #199
