### ISSUE TITLE
Use PouchDB instead of MockDB for development

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#601]
For local development we currently have the Mockdatabase which provides an in memory version of a database. Die Database comes with some limitations like the indices that have not yet been implemented and have to be maintained manually.
A solution to this overhead would be to just use a local version of the PouchDB.

- [x] Default to local PouchDB
- [ ] Button on login page that asks if demo data should be initialized (only when `useTemporaryDatabase: true`)
- [ ] Restructure session so it can use either only local, only remote or local and remote session -->  #701

**Comment by sleidig** [comment]
by default, the system is using the pouchdb in-memory adapter now (in "mock" session_type). Alternatively the "local" session_type can be set in the config.json to actually work with the browser's persisten IndexedDB without a server counterpart. Both do not require our own mocked indices and work identically, so there shouldn't be any functional differences or confusions --> closed

Some refactoring to simplify the session-service(s) would still be nice but we have a separate issue for that in #701
