### ISSUE TITLE
Move details from Entities into config

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#614]
Entity classes, especially `Child`, hold a lot of fields that have no explicit complex business logic and could be moved to the config. That would make these classes more simple and for example also allow other users to change the data type from a text to a select without issues.

Only very special fields with business logic should remain in the classes (e.g. the interactionType of Note, because it determines behaviour between meeting notes and other notes). Fields that are just there to hold some value can be moved to config. The demo generators can be adapted to generate values for fields defined in the default config without requiring the properties to be part of the class.

also see #894

**Comment by christophscheuing** [comment]
Do you want me to do more or less the same for child.ts as I have done for school.ts implementing #894? Please have a look at Pull Request "Improving german translation of config fix" to see if that makes sense to you.

**Comment by sleidig** [comment]
yes, that looks good! We could also move some Child properties completely out of the class into config-fix:
- religion
- motherTongue
