### ISSUE TITLE
Make Child.center a configurable enum

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#618]
The "center" field should be a dropdown form element rather than free text.

- [x] change the `center` property of the Child entity to type configurable-enum
- [x] adapt the child details form config for the field
- [x] adapt the child list config for the column
- [x] adapt the child list filter toggle for centers
- [x] ~adapt the `ChildrenCountDashboardComponent` to support grouping by configurable-enum values~ (done in earlier PR)

**Comment by Schottkyc137** [comment]
When initially opening the child-details component, the initial value of the center property is not set. Is this a bug or is there more to do from my side?

**Comment by sleidig** [comment]
This sounds like a bug. For other enum fields it seems to load correctly for me. Is this for all existing children's details?

**Comment by Schottkyc137** [comment]
I fixed it by adding the center to the child-entity attributes, so fortunately no bug
