### ISSUE TITLE
Generalize ASER results: configurable subjects and levels

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#630]
The ASER feature (basic literacy levels of students) is not allowing any adaption to user context at the moment. Even subjects/languages are hard coded. Using our new configuration system this can be made more flexible:

- The subjects (shown as columns) should be defined in the config.
- The levels (dropdown values representing the performance of a student) should be configurable as ConfigurableEnum types.

https://github.com/Aam-Digital/ndb-core/tree/master/src/app/child-dev-project/aser

**Comment by Schottkyc137** [comment]
This raises the issue how to implement functionalities such as `isReadingPassedOrNA` which is dependent on the particular implementation of the arrays?
