### ISSUE TITLE
Sorting by Category of Note not working

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#684]
**Describe the bug**
The sorting by category of note does not work

**To Reproduce**
1. Go to 'Notes'
2. Click on 'Category'
3. Nothing changes

**Expected behavior**
The notes should be sorted descending or ascending

**Additional context**
This is probably due to the loading of the category based on the config. Maybe instead of sorting by activity a filter could be created.

**Comment by Schottkyc137** [comment]
This is the same for all data-entries that are configurable enums (e.g. also happens in notes).
Can be fixed by altering the entity-list-component's sorting data accessor
