### ISSUE TITLE
Sorting broken in list of student within schools view

### ISSUE THREAD

**Issue by christophscheuing** [Aam-Digital/ndb-core#688]
Sorting in the table of students shown within the view of a school doesn't work any more.

**To Reproduce**
1. Go to 'School'
2. Click on the name of a school
3. Click on students to show the list of students attending this school
4. Click on 'PN', 'Name', 'Class' or 'Age' in the top row of the table

**Expected behavior**
Table should be sorted according to the row clicked on.

**Comment by Schottkyc137** [comment]
Someone forget to define a MatSort for this component. I will push the fix to branch fix_sort
