### ISSUE TITLE
Make EntityMapper's return an Observable

### ISSUE THREAD

**Issue by Schottkyc137** [Aam-Digital/ndb-core#692]
As of now, the way to load all objects of a type is using the entity-mapper's loadType-functionality. This works well when there is a constant amount of data to be loaded that can only change through one channel.
However, this does not work well, for example using the notes-list. Notes can both be added from an outside source (the primary action) as well as from the new-button. When adding this via the primary-action, it is very hard to route the way back to an open notes-list component (if there is any).

**Objective**
Find a way to load the data from the database but also enable continuous updates that can be seen on screen.

**Proposed Solutions & Alternatives**
A second function (for example `loadAll`) could be added, that - instead of a promise - would return an Observable. This would not emit all loaded values at once, but each value one-by one. The observable can be subscribed to - the subscription should stay active as long as the view is active. This way, notes or other data that is provided from an "outside" source can be added and seen on the screen directly.

**Additional context**
See the branch [entity-mapper-test](https://github.com/Aam-Digital/ndb-core/tree/entity_mapper_test) and especially the addition to [entity-mapper-service](https://github.com/Aam-Digital/ndb-core/blob/a1a11847ea3b7c697753864f39937f7a7c1dea9e/src/app/core/entity/entity-mapper.service.ts#L105) as an example. This function is not intended to replace old functionality, but add new one that can be used by several modules that need it.
See Issue #554

**Comment by sleidig** [comment]
Thanks for picking up this broader topic (and sorry for the slow response ...)!

I think subscribing to updates will be a great addition. I am a bit undecided whether it would be easier to understand if we completely separate the loading of initial data and the subscribing to update events. The interface is still a bit confusing/complex.

We also need to check and test that we don't inadvertently trick Angular change detection by updating existing objects. As far as I know change detection usually only notices if the reference of an @Input is changed, not if elements within are updated. Not sure what that means for editing arrays as data sources for some of our components.

This is a great start! Let's discuss further details at a meeting.
