### ISSUE TITLE
Children that were added are not removed when cancelling

### ISSUE THREAD

**Issue by Schottkyc137** [Aam-Digital/ndb-core#695]
When adding a child in the Note-details-component and one cancels the process, the child is still there in the list, and when re-opening the note

**To Reproduce**
1. Go to 'Notes'
2. Click on A Note
3. Add a Child (in the Children Section)
4. Click Cancel
5. The child is on the list

**Expected behavior**
The child should not be in the note's list when one cancels the process

**Assumed reason**
The copy of a chosen note is only shallow - the child-array is not copied but a reference to the original note.

**Comment by sleidig** [comment]
Good find. I can confirm this :+1:
