### ISSUE TITLE
Simplify and refactor the SessionService

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#701]
The SessionService interface and the SyncedSessionService should be further simplified:

- [ ] `sync` should not be part of the public interface. All sync related logic should probably be handled by the SyncedSessionService internally?
- [x] the old `LocalSession` implementation used internally in the SyncedSessionService should be replaced and use the `NewLocalSessionService` instead, which can also be used as a stand-alone service if only local session is required
- [x] `StateHandler` implementation is rather similar to Observable. It would be easier to work with this if the widely used Observable interface replaces the custom StateHandler. Maybe we can simply use BehaviourSubject instead.
- [x] database.provider probably doesn't have to depend

**Comment by sleidig** [comment]
@TheSlimvReal should we close this one - or are there any other ideas to simplify the code?

**Comment by TheSlimvReal** [comment]
Yes, you are right. I think we did all we had in mind when doing the session/startup refactoring in #1259
