### ISSUE TITLE
Avoid or optimize PouchDB Indexing

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#711]
Building indices after an initial sync of existing data is taking dozens of minutes even on a fast machine. As we have added more and more indices recently this is becoming a problematic issue. Collecting problem and possible approaches here.
As indices are not synced but always built locally this is adding a lot of load (and delay) to the user's device after the first sync.

One way could be to try and avoid indices where possible and work more with the native _id or in-memory filtering and caching.

Context & backgrounds:

- https://github.com/pouchdb-community/pouchdb-quick-search/issues/22#issuecomment-71411936
- https://github.com/pouchdb-community/pouchdb-quick-search/issues/22#issuecomment-191248252
- ...

**Comment by TheSlimvReal** [comment]
Thats an important issue. I have some ideas which need to be evaluated.

1. Make objects more complex to avoid needing indexes for loading related objects (see #693).
2. Make more calculations _in memory_ like we currently do in the `MockDatabase` which in my opinion still has a quite good performance for the fact that it is not optimized at all.
3. Check whether the [pouchdb in memory adapter](https://github.com/pouchdb-community/pouchdb-memory) achieves a better performance.

**Comment by TheSlimvReal** [comment]
The indices are not so much of a problem at the moment. Closing this for now. In case performance becomes a problem again, a new issue can be opened
