### ISSUE TITLE
Navigation menu unreachable

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#715]
**To Reproduce**
1. Open the developer tools
2. Resize the application until the button for opening and closing the navigation menu appears
3. Close the navigation menu
4. Close the developer tools which should also bring the application back to non-mobile mode
5. Now the navigation menu is still closed but the button to open the menu also dissappeard

**Expected behavior**
The navigation menu should open when the application is in normal mode

**Comment by sleidig** [comment]
Good find. I would suggest to always allow users to show/hide the navigation menu to resolve this.
