### ISSUE TITLE
Default sorting of school in alphabetical order

### ISSUE THREAD

**Issue by christophscheuing** [Aam-Digital/ndb-core#721]
When opening the school list (table), the school entries seem to be sorted by their UUID. It would make more sense to have the schools sorted by their name in ascending alphabetical order by default. This is especially the case when (mis)using the schools for other entries (like classes as "Hindi I, Hindi II, English I, English II").

Maybe we should also save the sorting selected by the user either just for the session or even to the user's settings in the database?

**Comment by sleidig** [comment]
That's a really good observation and suggestion. It should get a smart default order.

I probably wouldn't save the sort order for a user however. While some users may like that, in other cases it is good that the UI returns to a sensible default state after reloading the page. And it adds quite a bit of complexity to the code, especially if we implement it in several individual components.

**Comment by sleidig** [comment]
also see PR #751 - this will resolve this issue for "list views" (using `EntityListComponent`), but we may want to implement the same for the `EntitySubrecordComponent`

**Comment by sleidig** [comment]
actually in child details sorting should remain according to date, so this issue is resolved with the given PR sorting the Schools List
