### ISSUE TITLE
Store (and bump) project version in one place

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#73]
We are currently saving the project version as an attribute of [`ConfigService`](https://github.com/NGO-DB/ndb-core/blob/master/src/app/config/config.service.ts). But there is also the project version through npm in [`package.json`](https://github.com/NGO-DB/ndb-core/blob/master/package.json). Can load the package.json version from the `ConfigService` instead? Or how do we handle this?

**Comment by fschoell** [comment]
Don't think that's possible. We can't read the package.json at runtime as it won't be available. Not sure if we need the package.json version anyways as we probably won't publish this package. However, if we need it the best way probably would be to introduce a npm command that bumps the version automatically in the required files. 

I'm moving this to a future milestone as it's not really affecting us currently.

**Comment by sleidig** [comment]
will be handled as part of #238
