### ISSUE TITLE
Current school not updating (at least on on mock database)

### ISSUE THREAD

**Issue by christophscheuing** [Aam-Digital/ndb-core#742]
**Describe the bug**
When updating the school that a child is currently attending in the SchoolHistory of this child, this is not reflected in the list of students attending this very school.

**To Reproduce**
1. Go to "Children" on the left, click on the first child (PN1, Achyut Verma in the sample data), fold out "Education" (so that you can see the SchoolHistory) and change the school that this child is currently attending (first entry in school history) to another one.
2. Click on "Schools" on the left, pick the school selected as the current school in step 1 and fold out "Students" in order to see the list of students attending this school at the moment.

**Expected behavior**
Normally the child for which the current school was changed in step 1 should be displayed among the students attending this school. Unfortunately this is not the case right now. The child changed in step one seems to be immediately cleared of the list of students at the school that was the child's current school before the change in step 1, but the child is not listed as a student at the school that has been marked as the child's new current school.

When testing, after a certain time the child seemed to appear at the new current school though. I could not find any logical explanation to that behavior ...

I've noticed that behavior especially with the mock database. I'm not sure if it is also true for the real database.

**Additional context**
BTW: In the ScholHistory unter "Education", the change takes effect immediately, meaning that the text "Currently attending 13 at Aaditya School (7)" is updated at the same moment as the change of the current school takes place.

**Comment by sleidig** [comment]
With the new in-memory mode (PR #750) this is not happening anymore.
