### ISSUE TITLE
Enable deleting of notes

### ISSUE THREAD

**Issue by christophscheuing** [Aam-Digital/ndb-core#744]
*As a user I want to be able to delete a note.*
A note might have been created just for testing or it might contain errors.

**Proposed Solutions & Alternatives**
Add a "Delete note" function via a "Delete" button when editing a note.

**Additional context**
This feature should probably also be enabled for event notes (in the attendance section).

**Comment by sleidig** [comment]
duplicate of #371 

The point is valid, however. Deleting should be possible, even if it should not be a common action.
