### ISSUE TITLE
Better sorting for numbers in string properties

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#757]
Some properties like schoolClass in the `PreviousSchoolsComponent` or projectNumber in the `ChildrenListComponent` are of type `string` but often contain numbers as well. These fields require the flexibility of strings to allow users adding a prefix or suffix or something completely different. At the same time, the alphabetical ordering feels "wrong":

- Actual string order: `["1", "10", "2", "3", "X"]`
- Expected order: `["1", "2", "3", "10", "X"]`

We had implemented a custom sort function for this, which (probably accidentally) was removed from active code:
https://github.com/Aam-Digital/ndb-core/blob/1ece1020023e0a252817882e153920c31ee2036d/src/app/child-dev-project/children/model/child.ts#L105-L121

Let's bring this back for the above mentioned columns (or maybe even for all string columns?) that can be sorted in tables.

**Comment by sleidig** [comment]
@Schottkyc137 , @TheSlimvReal  can we assign columns to this sorting through config? (or do it for every string)
Project numbers should also be sorted with the numerical logic.

**Comment by TheSlimvReal** [comment]
Currently, all strings are converted to a number if possible ([here](src/app/core/entity-components/entity-subrecord/entity-subrecord/sorting-accessor.ts) is the the exact transformation) . This means if project numbers are numbers, it will already work. if project numbers also contain string literals, it wont work.

**Comment by TheSlimvReal** [comment]
The expected order is currently achieved in the app. Therefore, I consider this issue closed.
