### ISSUE TITLE
Create generic role concept

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#766]
Currently, the only roles in the app are admin and not-admin. This should be extended to a generic role concept which can be used to limit certain functionality or deny access to information. 

The available user roles should defined in the config. These roles can then be assigned to a user (by a admin user) and will be stored in the according user document in the `_users` db.

**Comment by sleidig** [comment]
User roles are now based on the _users couchdb table and can be used flexibly in our config-based system to hide or disable components (see #947)
