### ISSUE TITLE
Create & edit users

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#771]
App administrators should be able to create new users and edit permissions of users and user groups. 

- [x] Admins can invite (new) users to their Aam Digital instance via email
- [x] Admins can assign roles to users
- [x] Admins can withdraw users access to the application

**Comment by TheSlimvReal** [comment]
When creating new users, it should also be possible to directly assign new roles to them. How do we display (and especially explain) which roles are available. Keycloak provides an endpoint for which roles are available, but then we should remove some of the default rules (e.g. `uma_authorization`...). Another option would be to only allow the rules mentioned in the `Config:Permissions` file.

**Comment by TheSlimvReal** [comment]
A general question about the user roles. If we show all available roles, users might start giving themselves roles, which allow them to see the _technical_ components (admin, import, ...) which we at least at the moment should rather hide. 

So how do we keep users from assigning themselves these roles? In the short term we could filter out one (some?) predefined roles in the backend, in the long run we might not need these technical components anymore.

**Comment by sleidig** [comment]
> When creating new users, it should also be possible to directly assign new roles to them. How do we display (and especially explain) which roles are available. Keycloak provides an endpoint for which roles are available, but then we should remove some of the default rules (e.g. `uma_authorization`...). Another option would be to only allow the rules mentioned in the `Config:Permissions` file.


Why don't we combine the two: take roles from Keycloak API and filter these to only show the ones matching roles actually used in our config?

I guess there is a permission to restricting who can add roles? Beyond that, I would allow any role to be assigned - we should replace in-app UI modules that are used only by tech support as soon as possible, anyway.

**Comment by TheSlimvReal** [comment]
done in #1472
