### ISSUE TITLE
Automatic Data Migrations on config changes

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#773]
In order to easily migrate old and deprecated data sets, it should be possible to run migration scripts whenever the version of the application is updated.

A migration script should always be referenced with a version of the app. The `UpdateManagerService` currently checks through the service worker if a new version is available. If a later version is available, the app should run all migrations between the old previous version and the new version of the app. The `LatestChangesDialogService` sets a item in the local storage with the current version number. This can be used to check from which to which version the app is updated. Migration scripts for older version should not be run again. 
I am not sure what happens if many users run the migrations locally before syncing with the remote database. If this will create a lot of conflicts, the migration should first check if it already took place on the remote db.

Alternatively, [pouchdb-migrate](https://github.com/eHealthAfrica/pouchdb-migrate) could be checked out. But I am not sure how well it works and documentary is rather sparse.

**Comment by sleidig** [comment]
We have over time established a reasonably smooth config migration approach:

- changes written to the database must only be done once, server-side using the admin API (ndb-admin)
- `ConfigService` has a generalized migration functionality to transform config "on-the-fly" in the client, without writing it to the db. This way, code can use the new config formats, while the stored config can be either old or new format for some time.
- see ConfigService `ConfigMigration` interface to implement migration functions
- these local migration functions can be copied to ndb-admin API and used there for an actual, server-side migration after all users have updated their client version.
