### ISSUE TITLE
Generating demo data shouldn't block browser completely

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#779]
Generating demo data takes some time and seems to grab every browser resource in a blocking mode. For example, on slow machines the warning "site is not responding" is shown and in the demo integrated in our website the popup with introductory explanations cannot be dismissed while in the background demo data is still generated.

Can we release CPU cycles periodically during this long running generation to allow the browser to respond to other events?

Also, maybe we should reduce the amount of children in the demo (again) to make it load and run faster ...

**Comment by sleidig** [comment]
Two approaches may resolve this:
- use bulkDocs to batch the pouchdb writes rather than calling pouchdb with every single entity (https://pouchdb.com/guides/bulk-operations.html#use-bulkdocs-to-write-many-docs)
- use [WebWorkers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) ([for Angular](https://angular.io/guide/web-worker)) to move the generation and/or writing to a separate thread, thereby avoiding to block the UI. This has some challenge as the DemoDataService.publishDemoData uses a lot of Angular Services (cannot simply be run in a webworker as a whole and would need to split out the most heavy calculations into webworkers).

We should benchmark what the most performance heavy parts are. Probably the database writes?

**Comment by TheSlimvReal** [comment]
With #1173 we have implemented the `_bulkDocs` approach which sped up the initial demo data generation a lot. Therefore, I think this issue is not critical anymore.
