### ISSUE TITLE
Rework Login Process: Introduce a remote session service

### ISSUE THREAD

**Issue by fschoell** [Aam-Digital/ndb-core#78]
We should decouple the session services to avoid bugs such like #70 and #31 and to generally make the login process more transparent. 

I think the best way to solve this is to introduce a remote and a local session service with seperate states. Might even be possible to abstract the session service and then only overwrite particular methods.

### Requirements/Considerations:
- [ ] Simple and robust initial login (when local DB has to be synced before login)
- [ ] Smooth UX during initial sync (minimize needed sync size, clear UI feedback, ...)
- [ ] Simple handling of online/offline login differences with robust fallbacks
- [ ] After offline login, redoing remote login later on in background?
- [ ] Keep all authentication (local/remote) encapsulated at one place only (i.e. simplify `User` and `Database` modules to remove/hide all related)

**Comment by sleidig** [comment]
Making this the thread to discuss a redesign of the login process overall, there are a few more points to consider:

* Currently we need to ensure that the password is only changed synchronuously in the local database and for the remote server (also see #75 )
* Keeping login information in the same database as other data produces huge delay for the first login on a new machine. At least we need to use an independent database for user data.

**Comment by fschoell** [comment]
Some thoughts:

> Keeping login information in the same database as other data produces huge delay for the first login on a new machine. At least we need to use an independent database for user data that we sync independently.

Is this delay actually a problem? A partly synced database is probably not usable anyways. Maybe we should perform a full sync every time a new user logs in before he can actually do anything. 

Seperating the databases could still be wise though.

Maybe we should think about another remote login process. I've came up with some possibilities to decouple the session handling so we won't have the double login, but it's probably too much of an overhead:

* Key authentication would eliminate the need to synchronize to the remote server as the password change would just concern the private key. But this is kind of a hassle to set up and a lot of overhead. 
* Some token based approach would be possible either, so every new user get's a token which he enters at the first login, and then we use refresh tokens to keep the sessions alive. However, this lowers security (we will lose control over the remote sessions) and as soon as we might lose a token (or worse, the server loses session information like the auth key), the sessions get invalid and the user needs to enter a new token (which, in contrast to a password, he won't remember or have with him all the time). 
* One time passwords to authenticate once, then get the authentication from the synced database. Every new user / new system gets a one time password, which he can use once to syncronize the database. In this database there will then be the authentication credentials for the remote server. But again, we would lose the control over the remote sessions (except we somehow generate authentication databases so each database holds different authentication credentials, but then we get a lot of overhead again). 
* Write a proxy authentication for the CouchDB server which does basically the same as the local authentication. Whenever a user tries to log in, it looks up the credentials in the database. This way the password change will automatically be propagated to the remote server by the standard database replication. However, there might be a delay (the user changes the password offline, the database won't be replicated, the next time he tries to login with the new password but the remote server still has holds the database with the old password), so we would need to work with some cookie based / refresh token authentication system, too (so we can increase the session length to a month or so). 

OR: We use pouchdb-authentication's `changePassword` method and it's just not possible to change the password if the user isn't online. We would still have the same login process, but it's the most simple solution.

**Comment by sleidig** [comment]
Usability mandates that the password must be same on all devices, otherwise we'll leave users in a mess of old and new passwords. So I think whatever the implementation, there is no way around restricting password changes to times when the user is online.

**Comment by Lorsbyjm** [comment]
@liwde I assigned you, because you are working on the login. Don't know if you solve this issue oranother problem.

**Comment by mspoeri** [comment]
Has someone already considered the usage of [KeyCloak](https://www.keycloak.org/index.html) as idendity provider?

**Comment by sleidig** [comment]
We should definitely consider some provider and/or library. However, we are making an "Offline First" App. Whatever we use, it is essential that users are able to login while there is no internet connection (as connectivity can be very unreliable for some of our target users). Would that be possible with KeyCloak?

**Comment by sleidig** [comment]
closing this as the big refactoring PR #246 is merged.

the points about pouchdb plugins for authentication can be discussed as part of #272
