### ISSUE TITLE
Handle document conflicts

### ISSUE THREAD

**Issue by fschoell** [Aam-Digital/ndb-core#79]
This will be the next important feature after the HELGO and architecture rewrite milestones. We need a way to handle document conflicts in the database.

**Comment by sleidig** [comment]
There will always be cases that cannot be resolved automatically (e.g. two users changing the name of the same person), so I suggest we design a simple UI two manually resolve any conflicts for this.

Smart automatic resolutions can be added later on as a bonus, if possible.
