### ISSUE TITLE
Warn about outdated databases

### ISSUE THREAD

**Issue by fschoell** [Aam-Digital/ndb-core#80]
We should warn the user if the database he uses hasn't been synced for a certain interval (like a week for example). The user should be informed about this because he/she is probably seeing outdated data and making changes has a high risk of causing document conflicts.

**Comment by Lorsbyjm** [comment]
#122

**Comment by codingfabi** [comment]
this is obsolete because of the implmenetation of live syncing. therefore, this issue will be closed.

**Comment by sleidig** [comment]
This is actually still relevant for times when live sync is paused because the app is offline. But for that we have a newer, pretty much duplicate issue already: #412 . We can consider adding an alert as part of that as well.
