### ISSUE TITLE
BMI Widget performance problems

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#800]
Currently, the calculations triggered by the `ChildrenBmiDashboardComponent` are extremely extensive, degrading performance of the whole app until they are finished. This needs to be improved

**Comment by TheSlimvReal** [comment]
The health checks are loaded with many database accesses. This can be drastically reduced with a simple index that sorts first by the childId and second by the date of the health check. This way only the first health check for each child needs to be looked at and only one database access is necessary.
