### ISSUE TITLE
CLEANUP: remove deprecated code

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#814]
Once not needed anymore for migrations or backward compatibility the following `@deprecated` code should be removed in a dedicated PR:

- AttendanceMigrationService
- NoteMigrationService
- ...?

_Please add to this list ..._

**Comment by TheSlimvReal** [comment]
- [ ] All migrations
- [ ] AttendanceMonth, AttendanceDay ...
- [ ] ChildSchoolRelation migration in ChildrenService
