### ISSUE TITLE
UX improvements for list view

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#845]
The design of the list views (e.g. the "Children" list) has some aspects that are confusing to users. The following redesign is suggested:
![image](https://user-images.githubusercontent.com/1682541/121142663-8632c800-c83c-11eb-8d82-34a077ba2962.png)

- [x] **simplify top section:** remove the elevation and reorder the top filter/action section a bit. Move the "Add" button, move the "export" button into a three-dot menu to hide this less used option from cluttering the interface.
- [x] **table column groups through "tabs"**: Try to style the controls to display different column groups as tabs. This way it is more intuitive what the controls will do and no danger of confusing them with the filters.
- [x] **Less columns for demo**: some fields are extremely specific. The default config set in code and used for the demo should just offer a few fields for each tab as illustration and remove some details. (e.g. remove some health checkups and document status fields completely from the entity)
- [x] **Health Tab:** the columns can be reordered in a more informative way. For example. Name / Gender / Age / DoB / BMI / the rest of info. Obtain the basic info first and the specific after giving clarity.

**Comment by TheSlimvReal** [comment]
Implemented with #1086
