### ISSUE TITLE
UX: Highlight current menu entry

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#846]
Guide users and show where they currently are by highlighting the selected menu entry. Ideally styling it similar to this draft to give the feel of a selected tab.

For details pages, the parent entry should still be highlighted (i.e. when viewing an individual child's details page).

![image](https://user-images.githubusercontent.com/1682541/121144920-b8ddc000-c83e-11eb-8592-3f9d23cf1611.png)

**Comment by TheSlimvReal** [comment]
fixed with #1086
