### ISSUE TITLE
Document Upload / Storing files

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#89]
*As a social worker I want to upload and download documents in Aam Digital in order to have all relevant information in one place.*

- Files to be uploaded could include contracts, scanned school results or photos (the profile photo as well other photos from events, etc.). 
- Files should be attachable to any entity (e.g. a student's record or a note).
- Options to upload exactly one file or as many files as the user wants.

**Proposed Solutions & Alternatives**
- implement as a new dataType for Entity properties: `file`, `file-multiple`
- implement edit/display components to upload / download the file(s) (like we implemented entity-select etc.)
- ? store/retrieve files using a light-weight microservice on our server, auth via user's existing keycloak token

**User Stories**
- [x] Upload a file from my computer through a file-upload form field
- [x] Download an uploaded file through a file-upload field.
- [x] Delete an uploaded file from the record and the server overall.
- [x] ? Replace a uploaded file with a new file in a single-file upload field, which results in a warning to the user and of confirmed, deletes the previous file before adding the new one.
- [ ] ... ?

**Comment by sleidig** [comment]
there might be a solution for local file access in the browser coming up: https://www.heise.de/developer/artikel/Native-File-System-API-Dateisystemzugriff-fuer-Websites-und-PWAs-im-Anflug-4505949.html?wt_mc=rss.developer.beitrag.atom

**Comment by sleidig** [comment]
blocked by #472

**Comment by TheSlimvReal** [comment]
A simple file server with REST API https://github.com/jveverka/file-server

Unfortunately it doesn't provide integration with an existing auth provider (Keycloak)

**Comment by TheSlimvReal** [comment]
Another very easy approach would be to use the [CouchDB](https://docs.couchdb.org/en/3.2.2-docs/intro/api.html?highlight=attachments#attachments)/[PouchDB](https://pouchdb.com/guides/attachments.html) attachment features.
This would have the benefits, that we do not need to implement any further services (huge benefit) and can use the existing permission feature.

Some considerations:
We should probably not make the normal replication with attachments but only sync the attachment meta data. We can then make a *on-demand* request for the attachment through the [CoucDB API](https://docs.couchdb.org/en/3.2.2-docs/api/document/common.html?highlight=attachments#retrieving-attachments-content). For this we might need to implement the respective endpoint in the replication backend.

Suggestion from a CouchDB developer:

> I wouldn’t go >10MB of attachment(s) per doc. Ideally keep it <1MB

> what you can do is have two databases, one with just docs and one with docs + attachments and you only replicate the former and fetch docs+attachments from the other one on-demand

Which means that when a user wants to upload a attachment, a mirrored doc is created in the second DB which holds the attachment.

**Comment by TheSlimvReal** [comment]
Otherwise the nest [file upload](https://docs.nestjs.com/techniques/file-upload) and [file streaming](https://docs.nestjs.com/techniques/streaming-files) features together with the node fs [file write](https://nodejs.org/en/knowledge/file-system/how-to-write-files-in-nodejs/) should be a not to complex approach for writing the API ourselves.
