### ISSUE TITLE
Tooltip doesnt open on mobile

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#891]
**Describe the bug**
When editing a form with descriptions for a field, the description tooltip cannot be seen on a mobile device.

**To Reproduce**
1. Open the app in mobile view
2. Go to a child
3. Click on 'Observations'
4. Click on '+'
5. Click on the '?'
6. No hint will open

**Expected behavior**
A little too tooltip should open describing this field

**Comment by kirtijadhav** [comment]
For mobile screen, the issue arises while observing the changes made to the tooltip is - when you long press on '?', then only the description tooltip appears.
