### ISSUE TITLE
clear, consistent behavior of "inactive" (make dropout more visible)

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#899]
*As a social worker I want to know about the dropout logic in order to mark children as inactive instead of deleting them.*
The delete button should only be used if e.g. a child was created by accident. In case a child drops out of the program, the dropout logic should be used instead. This will automatically mark the child as inactive, once a dropout date has been set.
Currently, most users don't know about this feature and therefore delete the children instead. In the delete popup, the user should be asked if instead the child should be marked as dropout.

**Objective**
This should inform the user about the dropout logic in order to not delete children but keep them in the system marked as inactive. That allows users to read up on old children later on.

**Proposed Solutions & Alternatives**
In the popup where the user is asked if the child should be deleted, there should be an option asking if the child should be marked as dropout and potentially show a datepicker which allows to select the dropout date etc.

**Additional context**
Currently all entities (school, child, recurring activity) use the same delete logic and in some cases, the dropout logic does not make sense. Only in the case for a child, this additional info should be shown.

**Comment by sleidig** [comment]
Very good points. I will think this through and write some user stories to highlight the dropout/inactive feature from all angles. This is a key aspect, we should maybe work through this thoroughly and add a couple of workflows and pointers.

considering also:
- how on technical level entities are marked as "inactive": #619
- how to count active children externally (for analytics and in the future also for billing of customers)
- if a child is actually deleted, what to do with the linked other documents? #874
- where to add a guide or documentation on the concept of "inactive" status, to explain that in detail?

**Comment by sleidig** [comment]
Users [YGSP] have accidentally marked records as "inactive" (through the checkbox property, because they were not fully aware what this implies). The project manager asked to have permissions for this state to get better control.

**Comment by sleidig** [comment]
a solution to turn the "inactive" status into a core feature, more deeply integrated into the UI, is discussed here currently: https://github.com/Aam-Digital/ndb-core/issues/1674#issuecomment-1731712668
