### ISSUE TITLE
Improve German translation setup

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#911]
The i18n test instance still has some bugs or config problems:

- ~[ ] some unlabeled fields in child details basic information~
- ~[ ] child details: error in console "t is undefined ... appConfigurableEnumOf"~

~e.g. https://demo-de.aam-digital.com/de/child/f2bbbc58-e67f-4883-8769-05e4999f9a21
(Login: user "demo", password "pass")~

**Comment by TheSlimvReal** [comment]
I think the German translation setup (`demo-de`) is not really needed any more because we already have it covered with the demo instance.

**Comment by sleidig** [comment]
agreed, let's tear down that instance.

@christophscheuing wanted to keep this issue open to do one more iteration of polishing the actual translations in general.
