### ISSUE TITLE
Change position for the "add new" button to make it visible on all screen sizes

### ISSUE THREAD

**Issue by kirtijadhav** [Aam-Digital/ndb-core#917]
*Change position of the '+' Mat Button*
When adding a new observation it is difficult to find the button as a mobile user.

To Reproduce

1. Open the app in mobile view
2. Go to a child
3. Click on 'Observations'
4. find '+' button (which is only visible after scrolling horizontally in the table)

**Expected Behavior**
Position of the button should be similar to other features e.g. Notes and Reports.

**Additional Reference**

![addnewbutton-notesandreport](https://user-images.githubusercontent.com/83791155/127548533-8baa450f-18c0-4485-9a52-677f4ac88078.PNG)

**Comment by TheSlimvReal** [comment]
A rather easy solution for this problem:

- [ ] Make the last column which hold the 'add'-button and the 'trash' and 'pencil' symbol the first column of each table
- [ ] (additional) Hide 'trash' icon in normal view and only show when in editing mode

**Comment by sleidig** [comment]
the buttons column is part of the `EntitySubrecordComponent`
