### ISSUE TITLE
Sync does not work after user is inactive for some time

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#935]
**Describe the bug**
The remote authentication is not refreshed automatically so if a user is not making changes for 10 minutes, the remote session expires. Any local changes after that are not synced (Network tab of developer console will show a 401 response).

**To Reproduce**
1. Log in
2. Edit an entity --> changes are synced as expected
3. Wait 10 minutes
4. Edit another entity --> changes are not synced to server, request receives 401

**Expected behavior**
As long as the user is logged in the frontend, the remote auth should be automatically kept alive so that syncing always works.

**Comment by TheSlimvReal** [comment]
with #956 this will be somewhat fixes by our own auth implementation (logged in for 2h, for each requests during that time the two hours start again). What is missing is a frontend feedback when the auth-cookie is expired. In this case the user should be logged out.

**Comment by TheSlimvReal** [comment]
One option could be to automatically logout the user if the cookie expires / requests of the PouchDB are returning 401.

**Comment by sleidig** [comment]
also see related #2044
