### ISSUE TITLE
Form field styling problem

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#962]
Currently the form fields used in the `EntityFormComponent` are set to a fixed length which results in the following styling problem:

<img width="196" alt="activity_small_formfield" src="https://user-images.githubusercontent.com/33730997/131662673-5880e0d1-c5f9-4e8c-96ca-6b79640f48f7.png">

In this case it would look better if the form field would span the entire screen.
The fixed width was used to create a good styling for the form fields that have a tooltip next to them:

<img width="449" alt="tooltip_normal" src="https://user-images.githubusercontent.com/33730997/131662914-1fc1c510-bcc2-4229-9f6b-765d06f47c89.png">

A solution to this problem would be to give the tooltip a fixed size and give the form field as much space as possible. This solves the styling when no tooltip is present but creates another problem:

<img width="348" alt="tooltip_fixed" src="https://user-images.githubusercontent.com/33730997/131663400-0412ddce-cf20-4d50-af88-ee2fd00b5623.png">

As can be seen, the div around the form field takes the full length, but some of the form fields have a fixed length of `180px` and therefore don't take up the whole space. This results in a big white gap between the form field and the tooltip icon.

A solution to this problem could be to give all the form fields a length of 100% (as some already have):

<img width="331" alt="tooltip_full" src="https://user-images.githubusercontent.com/33730997/131664113-0f776fde-5a9c-44e2-9579-37ed621ccc6b.png">

This looks rather good on most screen sizes but in some cases the form fields get very big.

Or to move the tooltip icon to the left:

<img width="317" alt="tooltip_right" src="https://user-images.githubusercontent.com/33730997/131664334-c9a0c9e9-5aa2-43c5-9cff-07f0aa03352f.png">

Which looks a little odd. Because not all fields have tooltip.

I prefer the full width option because it would create make the form fields more common. An alternative would also be to just make a customized component for the participants section in the recurring activities (instead of using the generic `EntityFormComponent`.

**Comment by sleidig** [comment]
We should try to keep the layout organized by having only one (or 2-3) different widths of form fields. But we can also look at that later with a broader design update of the form component.
