### ISSUE TITLE
Add "divers" or "non-binary" as possible gender option

### ISSUE THREAD

**Issue by niborus** [Aam-Digital/ndb-core#965]
The german federal constitutional court ruled [2017 (ger)](https://www.bundesverfassungsgericht.de/SharedDocs/Pressemitteilungen/DE/2017/bvg17-095.html) that a third **not-empty** gender option is required in the civil status, which was put into law in [12/2018 (ger)](https://www.bmi.bund.de/SharedDocs/pressemitteilungen/DE/2018/12/drittes-geschlecht.html).

Non-binary children exist and must not be forced to get categorized under the wrong gender. Schools can not use this tool if it doesn't allow to enter unadulterated data of the children.

The Child-Gender-Model and all statistics and reportes derived therefrom should be updated to fit the real world.

**Comment by sleidig** [comment]
Thanks for filing this issue!

This is a configuration change but we should probably add this to our demo config (config-fix.ts) to demonstrate our awareness and support. And that config is also the starting point for customized setups of other clients.

**Comment by sleidig** [comment]
@niborus can you provide the official (or rather most commonly used) term in English language countries? Should we use "X"?
For the German translation we would use "divers", I think.

**Comment by niborus** [comment]
> @niborus can you provide the official (or rather most commonly used) term in English language countries? Should we use "X"?

I think we should be fine with "Non-binary/third gender" as a full name (see [mozilla/inclusion](https://github.com/mozilla/inclusion/blob/master/data-metrics/surveys/en/gender-identity.md#gender-identity-1)) and "X" as the single-character-acronym.

> For the German translation we would use "divers", I think.

Seems good.
