### ISSUE TITLE
Remember the expand state of a section in order to enable going back to that state with the back button

### ISSUE THREAD

**Issue by christophscheuing** [Aam-Digital/ndb-core#985]
When on the details view of a child the user opens the "Education" section and then clicks on a school name, she/he ist directed to the details view of that school. When then clicking on the back button (on the app or on the browser), then user gets back to the details view of that child. However the "Education" section is not expanded any longer, but closed. This is not what the user expects. It would feel more natural to get back to the details view of the child with the "Education" section being unfolded, as the user left it before.

The feature of remembering to fold / unfold the state of the sections probably might apply to other parts of the app as well and might add some more comfort to the user experience.

Technically this would probably imply saving the state in the URL or using query parameters (?).

**Comment by sleidig** [comment]
obsolete due to UX Redesign
